function [u_s] = concise_solver_u_core(visc_s, visc, AGlen_s, para)
% Inputs:
% visc_s [Pa a]
% visc [Pa a]

% Outputs:
% u_s [m a-1]

global Ms N dx dzeta H_s W W_s dzetadx dzetadx_s dhSdx_s zeta

% physical constants and parameters
rhoi = para.rhoi;
g = para.g;
is_SBC_width = para.is_SBC_width;
is_flowband = para.is_flowband;
f_nye = para.f_nye;
n = para.n;

% coefficients for linear systems
L1 = 4*visc_s;
L2 = 4*visc_s.*dzetadx_s.^2 + visc_s./(ones(N,1)*H_s).^2;
L3 = 8*dzetadx_s.*visc_s;

L4 = zeros(N,Ms);
L5 = zeros(N,Ms);
L6 = zeros(N,Ms);

Ls1 = zeros(1,Ms);
Ls2 = zeros(1,Ms);
LsW = zeros(1,Ms);

LHS = zeros(N*Ms, N*Ms);
RHS = zeros(N*Ms,1);

% shallow ice approximation (SIA)
sia = @(y,x) -2*AGlen_s(y,x)/(n+1)*(rhoi*g*dhSdx_s(x))^n *...
    (H_s(x)^(n+1) - (H_s(x)-H_s(x)*zeta(y)).^(n+1));
%%
%------------------------------Build main----------------------------------
for i = 2:Ms-1
    for j = 2:N-1
        k = (i-1)*N + j;
        RHS(k,1) = f_nye*rhoi*g*dhSdx_s(i);

        if i==2
            L4(j,i) = 4*visc_s(j,i)*(-4*dzetadx_s(j,i-1)+3*dzetadx_s(j,i)+dzetadx_s(j,i+1))/(3*dx) + ...
                4*visc_s(j,i)*dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta) + ...
                4*dzetadx_s(j,i)*(-4*visc_s(j,i-1)+3*visc_s(j,i)+visc_s(j,i+1))/(3*dx) + ...
                (visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)*(4*dzetadx_s(j,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(j,i)*visc_s(j,i)/W_s(j,i) * ...
                ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx) +...
                dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L4(N,i) = 4*visc_s(N,i)*(-4*dzetadx_s(N,i-1)+3*dzetadx_s(N,i)+dzetadx_s(N,i+1))/(3*dx) + ...
                4*visc_s(N,i)*dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta) + ...
                4*dzetadx_s(N,i)*(-4*visc_s(N,i-1)+3*visc_s(N,i)+visc_s(N,i+1))/(3*dx) + ...
                (3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)*(4*dzetadx_s(N,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(N,i)*visc_s(N,i)/W_s(N,i) * ...
                ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L4(1,i) = 4*visc_s(1,i)*(-4*dzetadx_s(1,i-1)+3*dzetadx_s(1,i)+dzetadx_s(1,i+1))/(3*dx) + ...
                4*visc_s(1,i)*dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta) + ...
                4*dzetadx_s(1,i)*(-4*visc_s(1,i-1)+3*visc_s(1,i)+visc_s(1,i+1))/(3*dx) + ...
                (-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)*(4*dzetadx_s(1,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(1,i)*visc_s(1,i)/W_s(1,i) * ...
                ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx) +...
                dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        elseif i==Ms-1
            L4(j,i) = 4*visc_s(j,i)*(-1*dzetadx_s(j,i-1)-3*dzetadx_s(j,i)+4*dzetadx_s(j,i+1))/(3*dx)+...
                4*visc_s(j,i)*dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta) +...
                4*dzetadx_s(j,i)*(-1*visc_s(j,i-1)-3*visc_s(j,i)+4*visc_s(j,i+1))/(3*dx) +...
                (visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)*(4*dzetadx_s(j,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(j,i)*visc_s(j,i)/W_s(j,i) * ...
                ((-1*W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx) +...
                dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L4(N,i) = 4*visc_s(N,i)*(-1*dzetadx_s(N,i-1)-3*dzetadx_s(N,i)+4*dzetadx_s(N,i+1))/(3*dx)+...
                4*visc_s(N,i)*dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta) +...
                4*dzetadx_s(N,i)*(-1*visc_s(N,i-1)-3*visc_s(N,i)+4*visc_s(N,i+1))/(3*dx) +...
                (3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)*(4*dzetadx_s(N,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(N,i)*visc_s(N,i)/W_s(N,i) * ...
                ((-1*W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L4(1,i) = 4*visc_s(1,i)*(-1*dzetadx_s(1,i-1)-3*dzetadx_s(1,i)+4*dzetadx_s(1,i+1))/(3*dx)+...
                4*visc_s(1,i)*dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta) +...
                4*dzetadx_s(1,i)*(-1*visc_s(1,i-1)-3*visc_s(1,i)+4*visc_s(1,i+1))/(3*dx) +...
                (-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)*(4*dzetadx_s(1,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(1,i)*visc_s(1,i)/W_s(1,i)*...
                ((-1*W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx) +...
                dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        else
            L4(j,i) = 4*visc_s(j,i)*(dzetadx(j,i)-dzetadx(j,i-1))/(dx)+...
                4*visc_s(j,i)*dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta) +...
                4*dzetadx_s(j,i)*(visc(j,i)-visc(j,i-1))/(dx) +...
                (visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)*(4*dzetadx_s(j,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(j,i)*visc_s(j,i)/W_s(j,i) *...
                ((W(j,i)-W(j,i-1))/(dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L4(N,i) = 4*visc_s(N,i)*(dzetadx(N,i)-dzetadx(N,i-1))/(dx)+...
                4*visc_s(N,i)*dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta) +...
                4*dzetadx_s(N,i)*(visc(N,i)-visc(N,i-1))/(dx) +...
                (3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)*(4*dzetadx_s(N,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(N,i)*visc_s(N,i)/W_s(N,i)*...
                ((W(N,i)-W(N,i-1))/(dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L4(1,i) = 4*visc_s(1,i)*(dzetadx(1,i)-dzetadx(1,i-1))/(dx)+...
                4*visc_s(1,i)*dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta) +...
                4*dzetadx_s(1,i)*(visc(1,i)-visc(1,i-1))/(dx) +...
                (-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)*(4*dzetadx_s(1,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(1,i)*visc_s(1,i)/W_s(1,i)*...
                ((W(1,i)-W(1,i-1))/(dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        end

        if i==2
            L5(j,i) = 4*(-4*visc_s(j,i-1)+3*visc_s(j,i)+visc_s(j,i+1))/(3*dx) +...
                4*dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta) + ...
                2*visc_s(j,i)/W_s(j,i)*...
                ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx) +...
                dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L5(N,i) = 4*(-4*visc_s(N,i-1)+3*visc_s(N,i)+visc_s(N,i+1))/(3*dx) +...
                4*dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta) + ...
                2*visc_s(N,i)/W_s(N,i)*...
                ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L5(1,i) = 4*(-4*visc_s(1,i-1)+3*visc_s(1,i)+visc_s(1,i+1))/(3*dx) +...
                4*dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta) + ...
                2*visc_s(1,i)/W_s(1,i)*...
                ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx) +...
                dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        elseif i==Ms-1
            L5(j,i) = 4*(-visc_s(j,i-1)-3*visc_s(j,i)+4*visc_s(j,i+1))/(3*dx) +...
                4*dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta) + ...
                2*visc_s(j,i)/W_s(j,i)*...
                ((-W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx) +...
                dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L5(N,i) = 4*(-visc_s(N,i-1)-3*visc_s(N,i)+4*visc_s(N,i+1))/(3*dx) +...
                4*dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta) + ...
                2*visc_s(N,i)/W_s(N,i)*...
                ((-W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L5(1,i) = 4*(-visc_s(1,i-1)-3*visc_s(1,i)+4*visc_s(1,i+1))/(3*dx) +...
                4*dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta) + ...
                2*visc_s(1,i)/W_s(1,i)*...
                ((-W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx) +...
                dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        else
            L5(j,i) = 4*(visc(j,i)-visc(j,i-1))/(dx) +...
                4*dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta) + ...
                2*visc_s(j,i)/W_s(j,i)*...
                ((W(j,i)-W(j,i-1))/(dx) +...
                dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L5(N,i) = 4*(visc(N,i)-visc(N,i-1))/(dx) +...
                4*dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta) + ...
                2*visc_s(N,i)/W_s(N,i)*...
                ((W(N,i)-W(N,i-1))/(dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L5(1,i) = 4*(visc(1,i)-visc(1,i-1))/(dx) +...
                4*dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta) + ...
                2*visc_s(1,i)/W_s(1,i)*...
                ((W(1,i)-W(1,i-1))/(dx) +...
                dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        end

        if is_flowband
            if i==2
                L6(j,i) = 2/W_s(j,i)*((-4*visc_s(j,i-1)+3*visc_s(j,i)+visc_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)) *...
                    ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)) +...
                    2*visc_s(j,i)/W_s(j,i)*(...
                    (8*W_s(j,i-1)-12*W_s(j,i)+4*W_s(j,i+1))/(3*dx^2) +...
                    dzetadx_s(j,i)^2*(W_s(j-1,i)-2*W_s(j,i)+W_s(j+1,i))/(dzeta^2) +...
                    2*dzetadx_s(j,i)*(-4*(W_s(j+1,i-1)-W_s(j-1,i-1)) +...
                    3*(W_s(j+1,i)-W_s(j-1,i))+(W_s(j+1,i+1)-W_s(j-1,i+1)))/(6*dx*dzeta) +...
                    (W_s(j+1,i)-W_s(j-1,i))/(2*dzeta) *...
                    ((-4*dzetadx_s(j,i-1)+3*dzetadx_s(j,i)+dzetadx_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta)) -...
                    ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta))^2/W_s(j,i)...
                    ) - visc_s(j,i)/W_s(j,i)^2;

                L6(N,i) = 2/W_s(N,i)*((-4*visc_s(N,i-1)+3*visc_s(N,i)+visc_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)) *...
                    ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)) +...
                    2*visc_s(N,i)/W_s(N,i)*(...
                    (8*W_s(N,i-1)-12*W_s(N,i)+4*W_s(N,i+1))/(3*dx^2) +...
                    dzetadx_s(N,i)^2*(W_s(N,i)-2*W_s(N-1,i)+W_s(N-2,i))/(dzeta^2) +...
                    2*dzetadx_s(N,i)*(-4*(3*W_s(N,i-1)-4*W_s(N-1,i-1)+W_s(N-2,i-1)) +...
                    3*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))+(3*W_s(N,i+1)-4*W_s(N-1,i+1)+W_s(N-2,i+1)))/(6*dx*dzeta) +...
                    (3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta) *...
                    ((-4*dzetadx_s(N,i-1)+3*dzetadx_s(N,i)+dzetadx_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta)) -...
                    ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta))^2/W_s(N,i)...
                    ) - visc_s(N,i)/W_s(N,i)^2;

                L6(1,i) = 2/W_s(1,i)*((-4*visc_s(1,i-1)+3*visc_s(1,i)+visc_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)) *...
                    ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)) +...
                    2*visc_s(1,i)/W_s(1,i)*(...
                    (8*W_s(1,i-1)-12*W_s(1,i)+4*W_s(1,i+1))/(3*dx^2) +...
                    dzetadx_s(1,i)^2*(W_s(1,i)-2*W_s(2,i)+W_s(3,i))/(dzeta^2) +...
                    2*dzetadx_s(1,i)*(-4*(-3*W_s(1,i-1)+4*W_s(2,i-1)+W_s(3,i-1)) +...
                    3*(-3*W_s(1,i)+4*W_s(2,i)+W_s(3,i))+(-3*W_s(1,i+1)+4*W_s(2,i+1)+W_s(3,i+1)))/(6*dx*dzeta) +...
                    (-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta) *...
                    ((-4*dzetadx_s(1,i-1)+3*dzetadx_s(1,i)+dzetadx_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta)) -...
                    ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta))^2/W_s(1,i)...
                    ) - visc_s(1,i)/W_s(1,i)^2;
            elseif i==Ms-1
                L6(j,i) = 2/W_s(j,i)*((-visc_s(j,i-1)-3*visc_s(j,i)+4*visc_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)) *...
                    ((-W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)) +...
                    2*visc_s(j,i)/W_s(j,i)*(...
                    (4*W_s(j,i-1)-12*W_s(j,i)+8*W_s(j,i+1))/(3*dx^2) +...
                    dzetadx_s(j,i)^2*(W_s(j-1,i)-2*W_s(j,i)+W_s(j+1,i))/(dzeta^2) +...
                    2*dzetadx_s(j,i)*(-(W_s(j+1,i-1)-W_s(j-1,i-1)) -...
                    3*(W_s(j+1,i-1)-W_s(j-1,i-1))+4*(W_s(j+1,i-1)-W_s(j-1,i-1)))/(6*dx*dzeta) +...
                    (W_s(j+1,i)-W_s(j-1,i))/(2*dzeta) *...
                    ((-dzetadx_s(j,i-1)-3*dzetadx_s(j,i)+4*dzetadx_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta)) -...
                    ((-W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta))^2/W_s(j,i)...
                    ) - visc_s(j,i)/W_s(j,i)^2;

                L6(N,i) = 2/W_s(N,i)*((-visc_s(N,i-1)-3*visc_s(N,i)+4*visc_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)) *...
                    ((-W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)) +...
                    2*visc_s(N,i)/W_s(N,i)*(...
                    (4*W_s(N,i-1)-12*W_s(N,i)+8*W_s(N,i+1))/(3*dx^2) +...
                    dzetadx_s(N,i)^2*(W_s(N,i)-2*W_s(N-1,i)+W_s(N-2,i))/(dzeta^2) +...
                    2*dzetadx_s(N,i)*(-(3*W_s(N,i-1)-4*W_s(N-1,i-1)+W_s(N,i-1)) -...
                    3*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N,i))+4*(3*W_s(N,i+1)-4*W_s(N-1,i+1)+W_s(N,i+1)))/(6*dx*dzeta) +...
                    (3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta) *...
                    ((-dzetadx_s(N,i-1)-3*dzetadx_s(N,i)+4*dzetadx_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta)) -...
                    ((-W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta))^2/W_s(N,i)...
                    ) - visc_s(N,i)/W_s(N,i)^2;

                L6(1,i) = 2/W_s(1,i)*((-visc_s(1,i-1)-3*visc_s(1,i)+4*visc_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)) *...
                    ((-W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)) + ...
                    2*visc_s(1,i)/W_s(1,i)*(...
                    (4*W_s(1,i-1)-12*W_s(1,i)+8*W_s(1,i+1))/(3*dx^2) +...
                    dzetadx_s(1,i)^2*(W_s(1,i)-2*W_s(2,i)+W_s(3,i))/(dzeta^2) +...
                    2*dzetadx_s(1,i)*(-(-3*W_s(1,i-1)+4*W_s(2,i-1)+W_s(3,i-1)) -...
                    3*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))+4*(-3*W_s(1,i+1)+4*W_s(2,i+1)-W_s(3,i+1)))/(6*dx*dzeta) +...
                    (-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta) *...
                    ((-dzetadx_s(1,i-1)-3*dzetadx_s(1,i)+4*dzetadx_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta)) -...
                    ((-W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta))^2/W_s(1,i)...
                    ) - visc_s(1,i)/W_s(1,i)^2;
            else
                L6(j,i) = 2/W_s(j,i)*((visc(j,i)-visc(j,i-1))/(dx) +...
                    dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)) *...
                    ((W(j,i)-W(j,i-1))/(dx) + ...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)) +...
                    2*visc_s(j,i)/W_s(j,i)*(...
                    (W_s(j,i-1)-2*W_s(j,i)+W_s(j,i+1))/(dx^2) +...
                    dzetadx_s(j,i)^2*(W_s(j-1,i)-2*W_s(j,i)+W_s(j+1,i))/(dzeta^2) +...
                    2*dzetadx_s(j,i)*(W_s(j+1,i+1)+W_s(j-1,i-1)-W_s(j+1,i-1)-W_s(j-1,i+1))/(4*dx*dzeta) +...
                    (W_s(j+1,i)-W_s(j-1,i))/(2*dzeta) *...
                    ((dzetadx(j,i)-dzetadx(j,i-1))/(dx) +...
                    dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta)) -...
                    ((W(j,i)-W(j,i-1))/(dx) +...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta))^2/W_s(j,i)...
                    ) - visc_s(j,i)/W_s(j,i)^2;

                L6(N,i) = 2/W_s(N,i)*((visc(N,i)-visc(N,i-1))/(dx) + ...
                    dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)) *...
                    ((W(N,i)-W(N,i-1))/(dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)) +...
                    2*visc_s(N,i)/W_s(N,i)*(...
                    (W_s(N,i-1)-2*W_s(N,i)+W_s(N,i+1))/(dx^2) +...
                    dzetadx_s(N,i)^2*(W_s(N,i)-2*W_s(N-1,i)+W_s(N-2,i))/(dzeta^2) +...
                    2*dzetadx_s(N,i)*((3*W_s(N,i+1)-4*W_s(N-1,i+1)+W_s(N-2,i+1)) -...
                    (3*W_s(N,i-1)-4*W_s(N-1,i-1)+W_s(N-2,i-1)))/(4*dx*dzeta) +...
                    (3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta) *...
                    ((dzetadx(N,i)-dzetadx(N,i-1))/(dx) +...
                    dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta)) -...
                    ((W(N,i)-W(N,i-1))/(dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta))^2/W_s(N,i)...
                    ) - visc_s(N,i)/W_s(N,i)^2;

                L6(1,i) = 2/W_s(1,i)*((visc(1,i)-visc(1,i-1))/(dx) +...
                    dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)) *...
                    ((W(1,i)-W(1,i-1))/(dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)) +...
                    2*visc_s(1,i)/W_s(1,i)*(...
                    (W_s(1,i-1)-2*W_s(1,i)+W_s(1,i+1))/(dx^2) +...
                    dzetadx_s(1,i)^2*(W_s(1,i)-2*W_s(2,i)+W_s(3,i))/(dzeta^2) +...
                    2*dzetadx_s(1,i)*((-3*W_s(1,i+1)+4*W_s(2,i+1)-W_s(3,i+1)) -...
                    (-3*W_s(1,i-1)+4*W_s(2,i-1)-W_s(3,i-1)))/(4*dx*dzeta) +...
                    (-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta) *...
                    ((dzetadx(1,i)-dzetadx(1,i-1))/(dx) +...
                    dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta)) -...
                    ((W(1,i)-W(1,i-1))/(dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta))^2/W_s(1,i)...
                    ) - visc_s(1,i)/W_s(1,i)^2;
            end
        end
        %------------------------------------LHS---------------------------
        if i==2
            LHS(k,k-N-1) = 2*L3(j,i)/(3*dx*dzeta);
            LHS(k,k-N) = 8*L1(j,i)/(3*dx^2) - 4*L5(j,i)/(3*dx);
            LHS(k,k-N+1) = -2*L3(j,i)/(3*dx*dzeta);
            LHS(k,k-1) = L2(j,i)/dzeta^2-L3(j,i)/(2*dx*dzeta) - L4(j,i)/(2*dzeta);
            LHS(k,k) = -4*L1(j,i)/(dx^2) - 2*L2(j,i)/dzeta^2 + L5(j,i)/dx+L6(j,i);
            LHS(k,k+1) = L2(j,i)/(dzeta^2) + L3(j,i)/(2*dx*dzeta) + L4(j,i)/(2*dzeta);
            LHS(k,k+N-1) = -L3(j,i)/(6*dx*dzeta);
            LHS(k,k+N) = 4*L1(j,i)/(3*dx^2) + L5(j,i)/(3*dx);
            LHS(k,k+N+1) = L3(j,i)/(6*dx*dzeta);

        elseif i==Ms-1
            LHS(k,k-N-1) = L3(j,i)/(6*dx*dzeta);
            LHS(k,k-N) = 4*L1(j,i)/(3*dx^2) - L5(j,i)/(3*dx);
            LHS(k,k-N+1) = -L3(j,i)/(6*dx*dzeta);
            LHS(k,k-1) = L2(j,i)/(dzeta^2) + L3(j,i)/(2*dx*dzeta) - L4(j,i)/(2*dzeta);
            LHS(k,k) = -4*L1(j,i)/(dx^2) - 2*L2(j,i)/dzeta^2 - L5(j,i)/dx + L6(j,i);
            LHS(k,k+1) = L2(j,i)/(dzeta^2) - L3(j,i)/(2*dx*dzeta) + L4(j,i)/(2*dzeta);
            LHS(k,k+N-1) = -2*L3(j,i)/(3*dx*dzeta);
            LHS(k,k+N) = 8*L1(j,i)/(3*dx^2) + 4*L5(j,i)/(3*dx);
            LHS(k,k+N+1) = 2*L3(j,i)/(3*dx*dzeta);

        else
            LHS(k,k-N-1) = L3(j,i)/(4*dx*dzeta);
            LHS(k,k-N) = L1(j,i)/(dx^2) - L5(j,i)/(2*dx);
            LHS(k,k-N+1) = -L3(j,i)/(4*dx*dzeta);
            LHS(k,k-1) = L2(j,i)/(dzeta^2) - L4(j,i)/(2*dzeta);
            LHS(k,k) = -2*L1(j,i)/(dx^2) - 2*L2(j,i)/dzeta^2 + L6(j,i);
            LHS(k,k+1) = L2(j,i)/dzeta^2 + L4(j,i)/(2*dzeta);
            LHS(k,k+N-1) = -L3(j,i)/(4*dx*dzeta);
            LHS(k,k+N) = L1(j,i)/(dx^2) + L5(j,i)/(2*dx);
            LHS(k,k+N+1) = L3(j,i)/(4*dx*dzeta);
        end
    end
end
%% Build surface BC (j=N)
for i = 1:Ms
    RHS((i-1)*N+N,1) = rhoi*g*dhSdx_s(i);
    Ls1(i) = 4*H_s(i)*dhSdx_s(i)/(1-4*H_s(i)*dzetadx_s(N,i)*dhSdx_s(i))*dzeta/dx;
    Ls2(i) = 4*H_s(i)*dhSdx_s(i)/(1-4*H_s(i)*dzetadx_s(N,i)*dhSdx_s(i))*dzeta/W_s(N,i);

    if is_SBC_width
        if i==1
            LsW(i) = (-8*W_s(N,i)+9*W_s(N,i+1)-W_s(N,i+2))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
        elseif i==2
            LsW(i) = (-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
        elseif i==Ms-1
            LsW(i) = (-W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
        elseif i==Ms
            LsW(i) = (8*W_s(N,i)-9*W_s(N,i-1)+W_s(N,i-2))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
        else
            LsW(i) = (W_s(N,i+1)-W_s(N,i-1))/(2*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
        end
    end
end

for i = 2:Ms-1
    if i==2
        LHS(i*N, (i-1)*N) = 8*L1(N,i)/(3*dx^2) - 8/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
            L3(N,i)*(64/3*Ls1(i-1)-4*Ls2(i-1)*LsW(i-1)-8*Ls1(i))/(6*dx*dzeta) - ...
            8/3*L4(N,i)*Ls1(i)/(2*dzeta) - 4*L5(N,i)/(3*dx);
        LHS(i*N, i*N-1) = 2*L2(N,i)/(dzeta^2);
        LHS(i*N, i*N) = -12*L1(N,i)/(3*dx^2) +...
            L2(N,i)*(2*Ls1(i)+Ls2(i)*LsW(i)-2)/(dzeta^2) + ...
            L3(N,i)*(-24*Ls1(i-1)+6*Ls1(i)+Ls2(i)*LsW(i)-Ls1(i+1))/(6*dx*dzeta) + ...
            L4(N,i)*(2*Ls1(i)+Ls2(i)*LsW(i))/(2*dzeta) + 3*L5(N,i)/(3*dx);
        LHS(i*N, (i+1)*N) = 4*L1(N,i)/(3*dx^2) + 2/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
            L3(N,i)*(8/3*Ls1(i-1)+2*Ls1(i)+Ls2(i+1)*LsW(i+1))/(6*dx*dzeta) + ...
            L4(N,i)*(2/3*Ls1(i))/(2*dzeta) + L5(N,i)/(3*dx);
        LHS(i*N, (i+2)*N) = L3(N,i)*Ls1(i+1)/(6*dx*dzeta);

    elseif i==Ms-1
        LHS(i*N,(i-2)*N) = L3(N,i)*Ls1(i-1)/(6*dx*dzeta);
        LHS(i*N,(i-1)*N) = 4*L1(N,i)/(3*dx^2) - 2/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
            L3(N,i)*(-Ls2(i-1)*LsW(i-1)+2*Ls1(i)+8/3*Ls1(i+1))/(6*dx*dzeta)...
            -2/3*L4(N,i)*Ls1(i)/(2*dzeta) - L5(N,i)/(3*dx);
        LHS(i*N,i*N-1) = 2*L2(N,i)/(dzeta^2);
        LHS(i*N,i*N) = -12*L1(N,i)/(3*dx^2) +...
            L2(N,i)*(-2*Ls1(i)+Ls2(i)*LsW(i)-2)/(dzeta^2) + ...
            L3(N,i)*(-Ls1(i-1)+6*Ls1(i)-3*Ls2(i)*LsW(i)-24*Ls1(i+1))/(6*dx*dzeta) + ...
            L4(N,i)*(-2*Ls1(i)+Ls2(i)*LsW(i))/(2*dzeta) - 3*L5(N,i)/(3*dx);
        LHS(i*N,(i+1)*N) = 8*L1(N,i)/(3*dx^2) + 8/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
            L3(N,i)*(-8*Ls1(i)+64/3*Ls1(i+1)+4*Ls2(i+1)*LsW(i+1))/(6*dx*dzeta) + ...
            8/3*L4(N,i)*Ls1(i)/(2*dzeta) + 4*L5(N,i)/(3*dx);

    else
        LHS(i*N,(i-2)*N) = L3(N,i)*Ls1(i-1)/(4*dx*dzeta);
        LHS(i*N,(i-1)*N) = L1(N,i)/(dx^2) - L2(N,i)*Ls1(i)/(dzeta^2) - ...
            L3(N,i)*Ls2(i-1)*LsW(i-1)/(4*dx*dzeta) -...
            L4(N,i)*Ls1(i)/(2*dzeta) - L5(N,i)/(2*dx);
        LHS(i*N,i*N-1) = 2*L2(N,i)/(dzeta^2);
        LHS(i*N,i*N) = -2*L1(N,i)/(dx^2) + L2(N,i)*(Ls2(i)*LsW(i)-2)/(dzeta^2) -...
            L3(N,i)*(Ls1(i-1)+Ls1(i+1))/(4*dx*dzeta) + L4(N,i)*Ls2(i)*LsW(i)/(2*dzeta);
        LHS(i*N,(i+1)*N) = L1(N,i)/(dx^2) + L2(N,i)*Ls1(i)/(dzeta^2) +...
            L3(N,i)*Ls2(i+1)*LsW(i+1)/(4*dx*dzeta) +...
            L4(N,i)*Ls1(i)/(2*dzeta) + L5(N,i)/(2*dx);
        LHS(i*N,(i+2)*N) = L3(N,i)*Ls1(i+1)/(4*dx*dzeta);
    end
end
%% Build basal BC (j=1)
%
for i = 2:Ms-1
    LHS((i-1)*N+1,(i-1)*N+1) = 1;
    RHS((i-1)*N+1,1) = 0;
end
%% Build lateral BC (i=1, i=Ms)
%
% head (i=1)
for j = 1:N
    LHS(j,j) = 1;
    RHS(j,1) = sia(j,1); % 
end

% terminus (i=Ms)
% terminus is set to zero velocity
for j = 1:N
    LHS((Ms-1)*N+j,(Ms-1)*N+j) = 1;
    RHS((Ms-1)*N+j,1) = sia(j,Ms);
end

%% Solve linear system
%
v = LHS\RHS;

% convert v to u_s
u_s = zeros(N, Ms);
for k = 1:N*Ms
    if fix(k/N)==k/N
        i = k/N;
    else
        i = fix(k/N) + 1;
    end
    j = k-(i-1)*N;
    
    u_s(j,i) = v(k);
end

end