function [u_s] = solver_u_subHydro(visc_s, visc, AGlen_s, Neff_s)
% Inputs:
% visc_s
% visc
% AGlen_s

% Outputs:
% u_s

global rho g n epsilon type_BBC beta2_s lambda_max m_max epr isFlowband
global Ms N dx dzeta H_s W W_s dzetadx dzetadx_s dhSdx_s dhBdx_s iter_u u_s_lst

L1 = 4*visc_s;
L2 = 4*visc_s.*dzetadx_s.^2 + visc_s./(ones(N,1)*H_s).^2;
L3 = 8*dzetadx_s.*visc_s;

L4 = zeros(N,Ms);
L5 = zeros(N,Ms);
L6 = zeros(N,Ms);

Ls1 = zeros(1,Ms);
Ls2 = zeros(1,Ms);
LsW = zeros(1,Ms);

% Lb1_LFL = zeros(1,Ms);
% Lb2_LFL = zeros(1,Ms);
Lb_CFL = zeros(1,Ms);

LHS = zeros(N*Ms, N*Ms);
RHS = zeros(N*Ms,1);
%------------------------------Build main----------------------------------
for i = 2:Ms-1
    for j = 2:N-1
        k = (i-1)*N + j;
        RHS(k,1) = rho*g*dhSdx_s(i);
        %-----------------------------L4-------------------------------
        if i == 2
            L4(j,i) = 4*visc_s(j,i)*(-4*dzetadx_s(j,i-1)+3*dzetadx_s(j,i)+dzetadx_s(j,i+1))/(3*dx)+ ...
                4*visc_s(j,i)*dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta) + ...
                4*dzetadx_s(j,i)*(-4*visc_s(j,i-1)+3*visc_s(j,i)+visc_s(j,i+1))/(3*dx) + ...
                (visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)*(4*dzetadx_s(j,i)^2+1/H_s(i)^2) + ...
                dzetadx_s(j,i)*(2*visc_s(j,i)/W_s(j,i))*...
                ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));
            
            L4(N,i) = 4*visc_s(N,i)*(-4*dzetadx_s(N,i-1)+3*dzetadx_s(N,i)+dzetadx_s(N,i+1))/(3*dx)+ ...
                4*visc_s(N,i)*dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta) + ...
                4*dzetadx_s(N,i)*(-4*visc_s(N,i-1)+3*visc_s(N,i)+visc_s(N,i+1))/(3*dx) + ...
                (3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)*(4*dzetadx_s(N,i)^2+1/H_s(i)^2) + ...
                dzetadx_s(N,i)*(2*visc_s(N,i)/W_s(N,i))*...
                ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));
            
            L4(1,i) = 4*visc_s(1,i)*(-4*dzetadx_s(1,i-1)+3*dzetadx_s(1,i)+dzetadx_s(1,i+1))/(3*dx) + ...
                4*visc_s(1,i)*dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta) + ...
                4*dzetadx_s(1,i)*(-4*visc_s(1,i-1)+3*visc_s(1,i)+visc_s(1,i+1))/(3*dx) + ...
                (-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)*(4*dzetadx_s(1,i)^2+1/H_s(i)^2) + ...
                dzetadx_s(1,i)*(2*visc_s(1,i)/W_s(1,i))*...
                ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
            
        elseif i == Ms-1
            L4(j,i) = 4*visc_s(j,i)*(-1*dzetadx_s(j,i-1)-3*dzetadx_s(j,i)+4*dzetadx_s(j,i+1))/(3*dx)+...
                4*visc_s(j,i)*dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta) +...
                4*dzetadx_s(j,i)*(-1*visc_s(j,i-1)-3*visc_s(j,i)+4*visc_s(j,i+1))/(3*dx) +...
                (visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)*(4*dzetadx_s(j,i)^2+1/H_s(i)^2) + ...
                dzetadx_s(j,i)*(2*visc_s(j,i)/W_s(j,i))*...
                ((-1*W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));
            
            L4(N,i) = 4*visc_s(N,i)*(-1*dzetadx_s(N,i-1)-3*dzetadx_s(N,i)+4*dzetadx_s(N,i+1))/(3*dx)+...
                4*visc_s(N,i)*dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta) +...
                4*dzetadx_s(N,i)*(-1*visc_s(N,i-1)-3*visc_s(N,i)+4*visc_s(N,i+1))/(3*dx) +...
                (3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)*(4*dzetadx_s(N,i)^2+1/H_s(i)^2) + ...
                dzetadx_s(N,i)*(2*visc_s(N,i)/W_s(N,i))*...
                ((-1*W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));
            
            L4(1,i) = 4*visc_s(1,i)*(-1*dzetadx_s(1,i-1)-3*dzetadx_s(1,i)+4*dzetadx_s(1,i+1))/(3*dx)+...
                4*visc_s(1,i)*dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta) +...
                4*dzetadx_s(1,i)*(-1*visc_s(1,i-1)-3*visc_s(1,i)+4*visc_s(1,i+1))/(3*dx) +...
                (-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)*(4*dzetadx_s(1,i)^2+1/H_s(i)^2) + ...
                dzetadx_s(1,i)*(2*visc_s(1,i)/W_s(1,i))*...
                ((-1*W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
            
        else
            L4(j,i) = 4*visc_s(j,i)*(dzetadx(j,i)-dzetadx(j,i-1))/(dx)+...
                4*visc_s(j,i)*dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta) +...
                4*dzetadx_s(j,i)*(visc(j,i)-visc(j,i-1))/(dx) +...
                (visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)*(4*dzetadx_s(j,i)^2+1/H_s(i)^2) + ...
                dzetadx_s(j,i)*(2*visc_s(j,i)/W_s(j,i))*...
                ((W(j,i)-W(j,i-1))/(dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));
            
            L4(N,i) = 4*visc_s(N,i)*(dzetadx(N,i)-dzetadx(N,i-1))/(dx)+...
                4*visc_s(N,i)*dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta) +...
                4*dzetadx_s(N,i)*(visc(N,i)-visc(N,i-1))/(dx) +...
                (3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)*(4*dzetadx_s(N,i)^2+1/H_s(i)^2) + ...
                dzetadx_s(N,i)*(2*visc_s(N,i)/W_s(N,i))*...
                ((W(N,i)-W(N,i-1))/(dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));
            
            L4(1,i) = 4*visc_s(1,i)*(dzetadx(1,i)-dzetadx(1,i-1))/(dx)+...
                4*visc_s(1,i)*dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta) +...
                4*dzetadx_s(1,i)*(visc(1,i)-visc(1,i-1))/(dx) +...
                (-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)*(4*dzetadx_s(1,i)^2+1/H_s(i)^2) + ...
                dzetadx_s(1,i)*(2*visc_s(1,i)/W_s(1,i))*...
                ((W(1,i)-W(1,i-1))/(dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        end
        %-----------------------------L5-------------------------------
        if i == 2
            L5(j,i) = 4*(-4*visc_s(j,i-1)+3*visc_s(j,i)+visc_s(j,i+1))/(3*dx) +...
                4*dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta) + ...
                2*visc_s(j,i)/W_s(j,i)*...
                ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));
            
            L5(N,i) = 4*(-4*visc_s(N,i-1)+3*visc_s(N,i)+visc_s(N,i+1))/(3*dx) +...
                4*dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta) + ...
                2*visc_s(N,i)/W_s(N,i)*...
                ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));
            
            L5(1,i) = 4*(-4*visc_s(1,i-1)+3*visc_s(1,i)+visc_s(1,i+1))/(3*dx) +...
                4*dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta) + ...
                2*visc_s(1,i)/W_s(1,i)*...
                ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
            
        elseif i == Ms-1
            L5(j,i) = 4*(-1*visc_s(j,i-1)-3*visc_s(j,i)+4*visc_s(j,i+1))/(3*dx) +...
                4*dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta) + ...
                2*visc_s(j,i)/W_s(j,i)*...
                ((-1*W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));
            
            L5(N,i) = 4*(-1*visc_s(N,i-1)-3*visc_s(N,i)+4*visc_s(N,i+1))/(3*dx) +...
                4*dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta) + ...
                2*visc_s(N,i)/W_s(N,i)*...
                ((-1*W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));
            
            L5(1,i) = 4*(-1*visc_s(1,i-1)-3*visc_s(1,i)+4*visc_s(1,i+1))/(3*dx) +...
                4*dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta) + ...
                2*visc_s(1,i)/W_s(1,i)*...
                ((-1*W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        else
            L5(j,i) = 4*(visc(j,i)-visc(j,i-1))/(dx) +...
                4*dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta) + ...
                2*visc_s(j,i)/W_s(j,i)*...
                ((W(j,i)-W(j,i-1))/(dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));
            
            L5(N,i) = 4*(visc(N,i)-visc(N,i-1))/(dx) +...
                4*dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta) + ...
                2*visc_s(N,i)/W_s(N,i)*...
                ((W(N,i)-W(N,i-1))/(dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));
            
            L5(1,i) = 4*(visc(1,i)-visc(1,i-1))/(dx) +...
                4*dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta) + ...
                2*visc_s(1,i)/W_s(1,i)*...
                ((W(1,i)-W(1,i-1))/(dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        end
        %-----------------------------L6-------------------------------
        if isFlowband
            if i == 2
                L6(j,i) = 2/W_s(j,i)*((-4*visc_s(j,i-1)+3*visc_s(j,i)+visc_s(j,i+1))/(3*dx)+...
                    dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta))*...
                    ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx) + dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)) +...
                    2*visc_s(j,i)/W_s(j,i)*((8*W_s(j,i-1)-12*W_s(j,i)+4*W_s(j,i+1))/(3*dx^2) + ...
                    dzetadx_s(j,i)^2*(W_s(j-1,i)-2*W_s(j,i)+W_s(j+1,i))/(dzeta^2) + ...
                    2*dzetadx_s(j,i)*(-4*(W_s(j+1,i-1)-W_s(j-1,i-1))+...
                    3*(W_s(j+1,i)-W_s(j-1,i))+(W_s(j+1,i+1)-W_s(j-1,i+1)))/(6*dx*dzeta) + ...
                    (W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)*...
                    ((-4*dzetadx_s(j,i-1)+3*dzetadx_s(j,i)+dzetadx_s(j,i+1))/(3*dx)+...
                    dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta)) -...
                    ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta))^2/W_s(j,i)) - ...
                    visc_s(j,i)/W_s(j,i)^2;
                
                L6(N,i) = 2/W_s(N,i)*((-4*visc_s(N,i-1)+3*visc_s(N,i)+visc_s(N,i+1))/(3*dx)+...
                    dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta))*...
                    ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)) +...
                    2*visc_s(N,i)/W_s(N,i)*((8*W_s(N,i-1)-12*W_s(N,i)+4*W_s(N,i+1))/(3*dx^2) + ...
                    dzetadx_s(N,i)^2*(W_s(N,i)-2*W_s(N-1,i)+W_s(N-2,i))/(dzeta^2) + ...
                    2*dzetadx_s(N,i)*(-4*(3*W_s(N,i-1)-4*W_s(N-1,i-1)+W_s(N-2,i-1))+...
                    3*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))+(3*W_s(N,i+1)-4*W_s(N-1,i+1)+W_s(N-2,i+1)))/(6*dx*dzeta) + ...
                    (3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)*...
                    ((-4*dzetadx_s(N,i-1)+3*dzetadx_s(N,i)+dzetadx_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta)) -...
                    ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta))^2/W_s(N,i)) - ...
                    visc_s(N,i)/W_s(N,i)^2;
                
                L6(1,i) = 2/W_s(1,i)*((-4*visc_s(1,i-1)+3*visc_s(1,i)+visc_s(1,i+1))/(3*dx)+...
                    dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta))*...
                    ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)) +...
                    2*visc_s(1,i)/W_s(1,i)*((8*W_s(1,i-1)-12*W_s(1,i)+4*W_s(1,i+1))/(3*dx^2) + ...
                    dzetadx_s(1,i)^2*(W_s(1,i)-2*W_s(2,i)+W_s(3,i))/(dzeta^2) +...
                    2*dzetadx_s(1,i)*(-4*(-3*W_s(1,i-1)+4*W_s(2,i-1)+W_s(3,i-1))+...
                    3*(-3*W_s(1,i)+4*W_s(2,i)+W_s(3,i))+(-3*W_s(1,i+1)+4*W_s(2,i+1)+W_s(3,i+1)))/(6*dx*dzeta) + ...
                    (-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)*...
                    ((-4*dzetadx_s(1,i-1)+3*dzetadx_s(1,i)+dzetadx_s(1,i+1))/(3*dx)+...
                    dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta)) -...
                    ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta))^2/W_s(1,i)) - ...
                    visc_s(1,i)/W_s(1,i)^2;
                
            elseif i == Ms-1
                L6(j,i) = 2/W_s(j,i)*((-1*visc_s(j,i-1)-3*visc_s(j,i)+4*visc_s(j,i+1))/(3*dx)+...
                    dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta))*...
                    ((-1*W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)) +...
                    2*visc_s(j,i)/W_s(j,i)*((4*W_s(j,i-1)-12*W_s(j,i)+8*W_s(j,i+1))/(3*dx^2) + ...
                    dzetadx_s(j,i)^2*(W_s(j-1,i)-2*W_s(j,i)+W_s(j+1,i))/(dzeta^2) +...
                    2*dzetadx_s(j,i)*(-1*(W_s(j-1,i-1)+W_s(j,i-1)+W_s(j+1,i-1))-...
                    3*(W_s(j-1,i)+W_s(j,i)+W_s(j+1,i))+4*(W_s(j-1,i+1)+W_s(j,i+1)+W_s(j+1,i+1)))/(6*dx*dzeta) +...
                    (W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)*...
                    ((-1*dzetadx_s(j,i-1)-3*dzetadx_s(j,i)+4*dzetadx_s(j,i+1))/(3*dx)+...
                    dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta)) -...
                    ((-1*W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta))^2/W_s(j,i)) - ...
                    visc_s(j,i)/W_s(j,i)^2;
                
                L6(N,i) = 2/W_s(N,i)*((-1*visc_s(N,i-1)-3*visc_s(N,i)+4*visc_s(N,i+1))/(3*dx)+...
                    dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta))*...
                    ((-1*W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)) +...
                    2*visc_s(N,i)/W_s(N,i)*((4*W_s(N,i-1)-12*W_s(N,i)+8*W_s(N,i+1))/(3*dx^2) + ...
                    dzetadx_s(N,i)^2*(W_s(N,i)-2*W_s(N-1,i)+W_s(N-2,i))/(dzeta^2) +...
                    2*dzetadx_s(N,i)*(-1*(3*W_s(N,i-1)-4*W_s(N-1,i-1)+W_s(N,i-1))-...
                    3*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N,i))+4*(3*W_s(N,i+1)-4*W_s(N-1,i+1)+W_s(N,i+1)))/(6*dx*dzeta) + ...
                    (3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)*...
                    ((-1*dzetadx_s(N,i-1)-3*dzetadx_s(N,i)+4*dzetadx_s(N,i+1))/(3*dx)+...
                    dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta)) -...
                    ((-1*W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta))^2/W_s(N,i)) - ...
                    visc_s(N,i)/W_s(N,i)^2;
                
                L6(1,i) = 2/W_s(1,i)*((-1*visc_s(1,i-1)-3*visc_s(1,i)+4*visc_s(1,i+1))/(3*dx)+...
                    dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta))*...
                    ((-1*W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)) + ...
                    2*visc_s(1,i)/W_s(1,i)*((4*W_s(1,i-1)-12*W_s(1,i)+8*W_s(1,i+1))/(3*dx^2) + ...
                    dzetadx_s(1,i)^2*(W_s(1,i)-2*W_s(2,i)+W_s(3,i))/(dzeta^2) + ...
                    2*dzetadx_s(1,i)*(-1*(-3*W_s(1,i-1)+4*W_s(2,i-1)+W_s(3,i-1))-...
                    3*(-3*W_s(1,i)+4*W_s(2,i)+W_s(3,i))+4*(-3*W_s(1,i+1)+4*W_s(2,i+1)+W_s(3,i+1)))/(6*dx*dzeta) + ...
                    (-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)*...
                    ((-1*dzetadx_s(1,i-1)-3*dzetadx_s(1,i)+4*dzetadx_s(1,i+1))/(3*dx)+...
                    dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta)) - ...
                    ((-1*W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta))^2/W_s(1,i)) - ...
                    visc_s(1,i)/W_s(1,i)^2;
            else
                L6(j,i) = 2/W_s(j,i)*((visc(j,i)-visc(j,i-1))/(dx) + dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta))*...
                    ((W(j,i)-W(j,i-1))/(dx) + dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)) +...
                    2*visc_s(j,i)/W_s(j,i)*((W_s(j,i-1)-2*W_s(j,i)+W_s(j,i+1))/(dx^2) + ...
                    dzetadx_s(j,i)^2*(W_s(j-1,i)-2*W_s(j,i)+W_s(j+1,i))/(dzeta^2) +...
                    2*dzetadx_s(j,i)*(W_s(j+1,i+1)+W_s(j-1,i-1)-W_s(j+1,i-1)-W_s(j-1,i+1))/(4*dx*dzeta) + ...
                    (W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)*...
                    ((dzetadx(j,i)-dzetadx(j,i-1))/(dx)+dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta)) -...
                    ((W(j,i)-W(j,i-1))/(dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta))^2/W_s(j,i)) - ...
                    visc_s(j,i)/W_s(j,i)^2;
                
                L6(N,i) = 2/W_s(N,i)*((visc(N,i)-visc(N,i-1))/(dx) + dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta))*...
                    ((W(N,i)-W(N,i-1))/(dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)) +...
                    2*visc_s(N,i)/W_s(N,i)*((W_s(N,i-1)-2*W_s(N,i)+W_s(N,i+1))/(dx^2) + ...
                    dzetadx_s(N,i)^2*(W_s(N,i)-2*W_s(N-1,i)+W_s(N-2,i))/(dzeta^2) + ...
                    2*dzetadx_s(N,i)*((3*W_s(N,i+1)-4*W_s(N-1,i+1)+W_s(N-2,i+1))-...
                    (3*W_s(N,i-1)-4*W_s(N-1,i-1)+W_s(N-2,i-1)))/(4*dx*dzeta) + ...
                    (3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)*...
                    ((dzetadx(N,i)-dzetadx(N,i-1))/(dx)+dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta)) -...
                    ((W(N,i)-W(N,i-1))/(dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta))^2/W_s(N,i)) - ...
                    visc_s(N,i)/W_s(N,i)^2;
                
                L6(1,i) = 2/W_s(1,i)*((visc(1,i)-visc(1,i-1))/(dx)+dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta))*...
                    ((W(1,i)-W(1,i-1))/(dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)) +...
                    2*visc_s(1,i)/W_s(1,i)*((W_s(1,i-1)-2*W_s(1,i)+W_s(1,i+1))/(dx^2) + dzetadx_s(1,i)^2*(W_s(1,i)-2*W_s(2,i)+W_s(3,i))/(dzeta^2) +...
                    2*dzetadx_s(1,i)*((-3*W_s(1,i+1)+4*W_s(2,i+1)-W_s(3,i+1))-(-3*W_s(1,i-1)+4*W_s(2,i-1)-W_s(3,i-1)))/(2*dx*dzeta) + ...
                    (-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)*...
                    ((dzetadx(1,i)-dzetadx(1,i-1))/(dx)+dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta)) -...
                    ((W(1,i)-W(1,i-1))/(dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta))^2/W_s(1,i)) - visc_s(1,i)/W_s(1,i)^2;
            end
        end
        %------------------------------------LHS-----------------------------------
        if i == 2
            LHS(k,k-N-1) = 2*L3(j,i)/(3*dx*dzeta);
            LHS(k,k-N) = 8*L1(j,i)/(3*dx^2)-4*L5(j,i)/(3*dx);
            LHS(k,k-N+1) = -2*L3(j,i)/(3*dx*dzeta);
            LHS(k,k-1) = L2(j,i)/dzeta^2-L3(j,i)/(2*dx*dzeta)-L4(j,i)/(2*dzeta);
            LHS(k,k) = -4*L1(j,i)/(dx^2)-2*L2(j,i)/dzeta^2+L5(j,i)/dx+L6(j,i);
            LHS(k,k+1) = L2(j,i)/(dzeta^2)+L3(j,i)/(2*dx*dzeta)+L4(j,i)/(2*dzeta);
            LHS(k,k+N-1) = -L3(j,i)/(6*dx*dzeta);
            LHS(k,k+N) = 4*L1(j,i)/(3*dx^2)+L5(j,i)/(3*dx);
            LHS(k,k+N+1) = L3(j,i)/(6*dx*dzeta);
            
        elseif i == Ms-1
            LHS(k,k-N-1) = L3(j,i)/(6*dx*dzeta);
            LHS(k,k-N) = 4*L1(j,i)/(3*dx^2)-L5(j,i)/(3*dx);
            LHS(k,k-N+1) = -L3(j,i)/(6*dx*dzeta);
            LHS(k,k-1) = L2(j,i)/(dzeta^2)+L3(j,i)/(2*dx*dzeta)-L4(j,i)/(2*dzeta);
            LHS(k,k) = -4*L1(j,i)/(dx^2)-2*L2(j,i)/dzeta^2-L5(j,i)/dx+L6(j,i);
            LHS(k,k+1) = L2(j,i)/(dzeta^2)-L3(j,i)/(2*dx*dzeta)+L4(j,i)/(2*dzeta);
            LHS(k,k+N-1) = -2*L3(j,i)/(3*dx*dzeta);
            LHS(k,k+N) = 8*L1(j,i)/(3*dx^2)+4*L5(j,i)/(3*dx);
            LHS(k,k+N+1) = 2*L3(j,i)/(3*dx*dzeta);
            
        else
            LHS(k,k-N-1) = L3(j,i)/(4*dx*dzeta);
            LHS(k,k-N) = L1(j,i)/(dx^2) - L5(j,i)/(2*dx);
            LHS(k,k-N+1) = -L3(j,i)/(4*dx*dzeta);
            LHS(k,k-1) = L2(j,i)/(dzeta^2) - L4(j,i)/(2*dzeta);
            LHS(k,k) = -2*L1(j,i)/(dx^2) - 2*L2(j,i)/dzeta^2 + L6(j,i);
            LHS(k,k+1) = L2(j,i)/dzeta^2 + L4(j,i)/(2*dzeta);
            LHS(k,k+N-1) = -L3(j,i)/(4*dx*dzeta);
            LHS(k,k+N) = L1(j,i)/(dx^2) + L5(j,i)/(2*dx);
            LHS(k,k+N+1) = L3(j,i)/(4*dx*dzeta);
        end
    end
end
%----------------------------Build surface BC (j=N)------------------------
for i = 1:Ms
    RHS((i-1)*N+N,1) = rho*g*dhSdx_s(i);
    Ls1(i) = 4*H_s(i)*dhSdx_s(i)/(1-4*H_s(i)*dzetadx_s(N,i)*dhSdx_s(i))*dzeta/dx;
    Ls2(i) = 4*H_s(i)*dhSdx_s(i)/(1-4*H_s(i)*dzetadx_s(N,i)*dhSdx_s(i))*dzeta/W_s(i);
    
    if i == 1
        LsW(i) = (-8*W_s(N,i)+9*W_s(N,i+1)-W_s(N,i+2))/(3*dx) + dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
    elseif i == 2
        LsW(i) = (-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) + dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
    elseif i == Ms-1
        LsW(i) = (-W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) + dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
    elseif i == Ms
        LsW(i) = (8*W_s(N,i)-9*W_s(N,i-1)+W_s(N,i-2))/(3*dx) + dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
    else
        LsW(i) = (W_s(N,i+1)-W_s(N,i-1))/(2*dx) + dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
    end
end
LsW = epsilon*LsW;

for i = 2:Ms-1
    if i == 2
        LHS(i*N, (i-1)*N) = 8*L1(N,i)/(3*dx^2) - 8/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
            L3(N,i)*(64/3*Ls1(i-1)-4*Ls2(i-1)*LsW(i-1)-8*Ls1(i))/(6*dx*dzeta) - ...
            8/3*L4(N,i)*Ls1(i)/(2*dzeta) - 4*L5(N,i)/(3*dx);
        LHS(i*N, i*N-1) = 2*L2(N,i)/(dzeta^2);
        LHS(i*N, i*N) = -12*L1(N,i)/(3*dx^2) + L2(N,i)*(2*Ls1(i)+Ls2(i)*LsW(i)-2)/(dzeta^2) + ...
            L3(N,i)*(-24*Ls1(i-1)+6*Ls1(i)+Ls2(i)*LsW(i)-Ls1(i+1))/(6*dx*dzeta) + ...
            L4(N,i)*(2*Ls1(i)+Ls2(i)*LsW(i))/(2*dzeta) + 3*L5(N,i)/(3*dx);
        LHS(i*N, (i+1)*N) = 4*L1(N,i)/(3*dx^2) + 2/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
            L3(N,i)*(8/3*Ls1(i-1)+2*Ls1(i)+Ls2(i+1)*LsW(i+1))/(6*dx*dzeta) + ...
            L4(N,i)*(2/3*Ls1(i))/(2*dzeta) + L5(N,i)/(3*dx);
        LHS(i*N, (i+2)*N) = L3(N,i)*Ls1(i+1)/(6*dx*dzeta);
        
    elseif i == Ms-1
        LHS(i*N,(i-2)*N) = L3(N,i)*Ls1(i-1)/(6*dx*dzeta);
        LHS(i*N,(i-1)*N) = 4*L1(N,i)/(3*dx^2) - 2/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
            L3(N,i)*(-Ls2(i-1)*LsW(i-1)+2*Ls1(i)+8/3*Ls1(i+1))/(6*dx*dzeta)...
            -2/3*L4(N,i)*Ls1(i)/(2*dzeta) - L5(N,i)/(3*dx);
        LHS(i*N,i*N-1) = 2*L2(N,i)/(dzeta^2);
        LHS(i*N,i*N) = -12*L1(N,i)/(3*dx^2) + L2(N,i)*(-2*Ls1(i)+Ls2(i)*LsW(i)-2)/(dzeta^2) + ...
            L3(N,i)*(-Ls1(i-1)+6*Ls1(i)-3*Ls2(i)*LsW(i)-24*Ls1(i+1))/(6*dx*dzeta) + ...
            L4(N,i)*(-2*Ls1(i)+Ls2(i)*LsW(i))/(2*dzeta) - 3*L5(N,i)/(3*dx);
        LHS(i*N,(i+1)*N) = 8*L1(N,i)/(3*dx^2) + 8/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
            L3(N,i)*(-8*Ls1(i)+64/3*Ls1(i+1)+4*Ls2(i+1)*LsW(i+1))/(6*dx*dzeta) + ...
            8/3*L4(N,i)*Ls1(i)/(2*dzeta) + 4*L5(N,i)/(3*dx);
        
    else
        LHS(i*N,(i-2)*N) = L3(N,i)*Ls1(i-1)/(4*dx*dzeta);
        LHS(i*N,(i-1)*N) = L1(N,i)/(dx^2) - L2(N,i)*Ls1(i)/(dzeta^2) - ...
            L3(N,i)*Ls2(i-1)*LsW(i-1)/(4*dx*dzeta) - L4(N,i)*Ls1(i)/(2*dzeta) - L5(N,i)/(2*dx);
        LHS(i*N,i*N-1) = 2*L2(N,i)/(dzeta^2);
        LHS(i*N,i*N) = -2*L1(N,i)/(dx^2) + L2(N,i)*(Ls2(i)*LsW(i)-2)/(dzeta^2) -...
            L3(N,i)*(Ls1(i-1)+Ls1(i+1))/(4*dx*dzeta) + L4(N,i)*Ls2(i)*LsW(i)/(2*dzeta);
        LHS(i*N,(i+1)*N) = L1(N,i)/(dx^2) + L2(N,i)*Ls1(i)/(dzeta^2) + L3(N,i)*Ls2(i+1)*LsW(i+1)/(4*dx*dzeta) +...
            L4(N,i)*Ls1(i)/(2*dzeta) + L5(N,i)/(2*dx);
        LHS(i*N,(i+2)*N) = L3(N,i)*Ls1(i+1)/(4*dx*dzeta);
    end
end
%-----------------------------Build basal BC (j=1)-------------------------
switch type_BBC
    case 1 % no-slip
        for i = 2:Ms-1
            LHS((i-1)*N+1,(i-1)*N+1) = 1;
            RHS((i-1)*N+1,1) = 0;
        end
    case 2 % Coulomb friction law (taub = sigma_xz)
        Cb = 0.84*m_max;
        Neff_s = zeros(1,Ms);
        frozen = zeros(1,Ms);
        for i = 1:Ms
            Neff_s(i) = epr(i)*rho*g*H_s(i);
            if iter_u == 1
                ubi = 0;
            else
                ubi = u_s_lst(1,i);
            end
            Lb_CFL(i) = 4*AGlen_s(1,i)*H_s(i)*dzeta*Cb(i)^n*Neff_s(i)^n*m_max(i)/...
                (ubi*m_max(i) + Cb(i)^n*Neff_s(i)^n*lambda_max(i)*AGlen_s(1,i)); % /(1+(H_s(i)/W_s(1,i))^2)
        end
        frozeni = 0;
        for i=2:Ms-1
            %         if T_lst(1,i) >= (273.15 - H(i)*8.7e-4 - 0.2) % local melting
            if T_lst(1,i) == (273.15 - H(i)*8.7e-4) % local melting
                if i == 2
                    LHS((i-1)*N+1,(i-2)*N+1) = 8*L1(1,i)/(3*dx^2) - 4*Lb_CFL(i-1)*L3(1,i)/(6*dx*dzeta) - 4*L5(1,i)/(3*dx);
                    LHS((i-1)*N+1,(i-1)*N+1) = -12*L1(1,i)/(3*dx^2) - (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) +...
                        3*L3(1,i)*Lb_CFL(i)/(6*dx*dzeta) + Lb_CFL(i)*L4(1,i)/(2*dzeta) + 3*L5(1,i)/(3*dx) + L6(1,i);
                    LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/dzeta^2;
                    LHS((i-1)*N+1,i*N+1) = 4*L1(1,i)/(3*dx^2) + Lb_CFL(i+1)*L3(1,i)/(6*dx*dzeta) + L5(1,i)/(3*dx);
                elseif i == Ms-1
                    LHS((i-1)*N+1,(i-2)*N+1) = 4*L1(1,i)/(3*dx^2) - Lb_CFL(i-1)*L3(1,i)/(6*dx*dzeta) - L5(1,i)/(3*dx);
                    LHS((i-1)*N+1,(i-1)*N+1) = -12*L1(1,i)/(3*dx^2) - (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) -...
                        3*Lb_CFL(i)*L3(1,i)/(6*dx*dzeta) + Lb_CFL(i)*L4(1,i)/(2*dzeta) - 3*L5(1,i)/(3*dx) + L6(1,i);
                    LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/dzeta^2;
                    LHS((i-1)*N+1,i*N+1) = 8*L1(1,i)/(3*dx^2) + 4*Lb_CFL(i+1)*L3(1,i)/(6*dx*dzeta) + 4*L5(1,i)/(3*dx);
                else
                    LHS((i-1)*N+1,(i-2)*N+1) = L1(1,i)/(dx^2) - Lb_CFL(i-1)*L3(1,i)/(4*dx*dzeta) - L5(1,i)/(2*dx);
                    LHS((i-1)*N+1,(i-1)*N+1) = -2*L1(1,i)/(dx^2) - (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) +...
                        Lb_CFL(i)*L4(1,i)/(2*dzeta) + L6(1,i);
                    LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
                    LHS((i-1)*N+1,i*N+1) = L1(1,i)/(dx^2) + Lb_CFL(i+1)*L3(1,i)/(4*dx*dzeta) + L5(1,i)/(2*dx);
                end
            else % frozen to bedrock
                frozeni = frozeni + 1; % number of the cold grids
                frozen(frozeni) = i; % position of the frozeni-th cold grid
                LHS((i-1)*N+1,(i-1)*N+1) = 1;
                RHS((i-1)*N+1,1) = 0;
            end
        end
    case 3 % linear sliding law
        Lb1_LFL = 4.*dzeta.*H_s.*dhBdx_s./(1 - 4.*H_s.*dhBdx_s.*dzetadx_s(1,:))./dx;
        Lb2_LFL = 2.*dzeta.*H_s.*beta2_s./visc_s(1,:)./(1 - 4.*H_s.*dhBdx_s.*dzetadx_s(1,:));
        
        for i = 2:Ms-1
            RHS((i-1)*N+1,1) = rho*g*dhSdx_s(i);
            if i == 2
                LHS((i-1)*N+1, (i-2)*N+1) = 8*L1(1,i)/(3*dx^2) + 8*Lb1_LFL(i)*L2(1,i)/(3*dzeta^2) +...
                    (64*Lb1_LFL(i-1)/3-4*Lb2_LFL(i-1)-8*Lb1_LFL(i))*L3(1,i)/(6*dx*dzeta) -...
                    8/3*Lb1_LFL(i)*L4(1,i)/(2*dzeta) - 4*L5(1,i)/(3*dx);
                LHS((i-1)*N+1, (i-1)*N+1) = -12*L1(1,i)/(3*dx^2) - (2+2*Lb1_LFL(i)+Lb2_LFL(i))*L2(1,i)/(dzeta^2) +...
                    (-24*Lb1_LFL(i-1)+6*Lb1_LFL(i)+3*Lb2_LFL(i)-Lb1_LFL(i+1))*L3(1,i)/(6*dx*dzeta) +...
                    (2*Lb1_LFL(i)+Lb2_LFL(i))*L4(1,i)/(2*dzeta) + 3*L5(1,i)/(3*dx) + L6(1,i);
                LHS((i-1)*N+1, (i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
                LHS((i-1)*N+1, i*N+1) = 4*L1(1,i)/(3*dx^2) - 2/3*Lb1_LFL(i)*L2(1,i)/(dzeta^2) +...
                    (8/3*Lb1_LFL(i-1)+2*Lb1_LFL(i)+Lb2_LFL(i+1))*L3(1,i)/(6*dx*dzeta) +...
                    2/3*Lb1_LFL(i)*L4(1,i)/(2*dzeta) + L5(1,i)/(3*dx);
            elseif i == Ms-1
                LHS((i-1)*N+1, (i-3)*N+1) = Lb1_LFL(i-1)*L3(1,i)/(6*dx*dzeta);
                LHS((i-1)*N+1, (i-2)*N+1) = 4*L1(1,i)/(3*dx^2) + 2/3*Lb1_LFL(i)*L2(1,i)/(dzeta^2) +...
                    (-Lb2_LFL(i-1)+2*Lb1_LFL(i)+8/3*Lb1_LFL(i+1))*L3(1,i)/(6*dx*dzeta) -...
                    2/3*Lb1_LFL(i)*L4(1,i)/(2*dzeta) - L5(1,i)/(3*dx);
                LHS((i-1)*N+1, (i-1)*N+1) = -12*L1(1,i)/(3*dx^2) + (-2+2*Lb1_LFL(i)-Lb2_LFL(i))*L2(1,i)/(dzeta^2) + ...
                    (-Lb1_LFL(i-1)+6*Lb1_LFL(i)-3*Lb2_LFL(i)-24*Lb1_LFL(i+1))*L3(1,i)/(6*dx*dzeta) +...
                    (-2*Lb1_LFL(i)+Lb2_LFL(i))*L4(1,i)/(2*dzeta) - 3*L5(1,i)/(3*dx) + L6(1,i);
                LHS((i-1)*N+1, (i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
                LHS((i-1)*N+1, i*N+1) = 8*L1(1,i)/(3*dx^2) - 8/3*Lb1_LFL(i)*L2(1,i)/(dzeta^2) +...
                    (-8*Lb1_LFL(i)+64/3*Lb1_LFL(i+1)+4*Lb2_LFL(i+1))*L3(1,i)/(6*dx*dzeta) +...
                    8/3*Lb1_LFL(i)*L4(1,i)/(2*dzeta) + 4*L5(1,i)/(3*dx);
            else
                LHS((i-1)*N+1, (i-3)*N+1) = Lb1_LFL(i-1)*L3(1,i)/(4*dx*dzeta);
                LHS((i-1)*N+1, (i-2)*N+1) = L1(1,i)/(dx^2) + Lb1_LFL(i)*L2(1,i)/(dzeta^2) - Lb2_LFL(i-1)*L3(1,i)/(4*dx*dzeta) -...
                    Lb1_LFL(i)*L4(1,i)/(2*dzeta) - L5(1,i)/(2*dx);
                LHS((i-1)*N+1, (i-1)*N+1) = -2*L1(1,i)/(dx^2) - (2+Lb2_LFL(i))*L2(1,i)/(dzeta^2) -...
                    (Lb1_LFL(i+1)+Lb1_LFL(i-1))*L3(1,i)/(4*dx*dzeta) + Lb2_LFL(i)*L4(1,i)/(2*dzeta) + L6(1,i);
                LHS((i-1)*N+1, (i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
                LHS((i-1)*N+1, i*N+1) = L1(1,i)/(dx^2) - Lb1_LFL(i)*L2(1,i)/(dzeta^2) +...
                    Lb2_LFL(i+1)*L3(1,i)/(4*dx*dzeta) + Lb1_LFL(i)*L4(1,i)/(2*dzeta) + L5(1,i)/(2*dx);
                LHS((i-1)*N+1, (i+1)*N+1) = Lb1_LFL(i+1)*L3(1,i)/(4*dx*dzeta);
            end
        end
    case 4 % simplified linear friction law
        Lb2_LFL = 2.*dzeta.*H_s.*beta2_s./visc_s(1,:);
        
        for i = 2:Ms-1
            RHS((i-1)*N+1,1) = rho*g*dhSdx_s(i);
            LHS((i-1)*N+1, (i-2)*N+1) = L1(1,i)/(dx^2) - Lb2_LFL(i-1)*L3(1,i)/(4*dx*dzeta) - L5(1,i)/(2*dx);
            LHS((i-1)*N+1, (i-1)*N+1) = -2*L1(1,i)/(dx^2) - (2+Lb2_LFL(i))*L2(1,i)/(dzeta^2) +...
                Lb2_LFL(i)*L4(1,i)/(2*dzeta) + L6(1,i);
            LHS((i-1)*N+1, (i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
            LHS((i-1)*N+1, i*N+1) = L1(1,i)/(dx^2) + Lb2_LFL(i+1)*L3(1,i)/(4*dx*dzeta) + L5(1,i)/(2*dx);
        end
    case 5 % Coulomb friction law (taub = sigma_xz) with effective pressure calculated by subhydrology model
        Cb = 0.84*m_max;
        frozen = zeros(1,Ms);        
        for i = 1:Ms
            if iter_u == 1
                ubi = 0;
            else
                ubi = u_s_lst(1,i);
            end
            Lb_CFL(i) = 4*AGlen_s(1,i)*H_s(i)*dzeta*Cb^n*Neff_s(i)^n*m_max/...
                (ubi*m_max + Cb^n*Neff_s(i)^n*lambda_max*AGlen_s(1,i)); % /(1+(H_s(i)/W_s(1,i))^2)
        end
        for i=2:Ms-1
                if i == 2
                    LHS((i-1)*N+1,(i-2)*N+1) = 8*L1(1,i)/(3*dx^2) - 4*Lb_CFL(i-1)*L3(1,i)/(6*dx*dzeta) - 4*L5(1,i)/(3*dx);
                    LHS((i-1)*N+1,(i-1)*N+1) = -12*L1(1,i)/(3*dx^2) - (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) +...
                        3*L3(1,i)*Lb_CFL(i)/(6*dx*dzeta) + Lb_CFL(i)*L4(1,i)/(2*dzeta) + 3*L5(1,i)/(3*dx) + L6(1,i);
                    LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/dzeta^2;
                    LHS((i-1)*N+1,i*N+1) = 4*L1(1,i)/(3*dx^2) + Lb_CFL(i+1)*L3(1,i)/(6*dx*dzeta) + L5(1,i)/(3*dx);
                elseif i == Ms-1
                    LHS((i-1)*N+1,(i-2)*N+1) = 4*L1(1,i)/(3*dx^2) - Lb_CFL(i-1)*L3(1,i)/(6*dx*dzeta) - L5(1,i)/(3*dx);
                    LHS((i-1)*N+1,(i-1)*N+1) = -12*L1(1,i)/(3*dx^2) - (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) -...
                        3*Lb_CFL(i)*L3(1,i)/(6*dx*dzeta) + Lb_CFL(i)*L4(1,i)/(2*dzeta) - 3*L5(1,i)/(3*dx) + L6(1,i);
                    LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/dzeta^2;
                    LHS((i-1)*N+1,i*N+1) = 8*L1(1,i)/(3*dx^2) + 4*Lb_CFL(i+1)*L3(1,i)/(6*dx*dzeta) + 4*L5(1,i)/(3*dx);
                else
                    LHS((i-1)*N+1,(i-2)*N+1) = L1(1,i)/(dx^2) - Lb_CFL(i-1)*L3(1,i)/(4*dx*dzeta) - L5(1,i)/(2*dx);
                    LHS((i-1)*N+1,(i-1)*N+1) = -2*L1(1,i)/(dx^2) - (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) +...
                        Lb_CFL(i)*L4(1,i)/(2*dzeta) + L6(1,i);
                    LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
                    LHS((i-1)*N+1,i*N+1) = L1(1,i)/(dx^2) + Lb_CFL(i+1)*L3(1,i)/(4*dx*dzeta) + L5(1,i)/(2*dx);
                end
        end
end
%---------------------Build end BC (i=1, i=Ms)------------------------
for j = 1:N
    LHS(j,j) = 1; % upper limit
    RHS(j,1) = 0;
    
    LHS((Ms-1)*N+j,(Ms-1)*N+j) = 1; % lower limit
    RHS((Ms-1)*N+j,1) = 0;
end
%----------------------------Solve linear system---------------------------
v = LHS\RHS;

u_s = zeros(N, Ms);
for k = 1:N*Ms
    if fix(k/N) == k/N
        i = k/N;
    else
        i = fix(k/N) + 1;
    end
    j = k-(i-1)*N;
    u_s(j,i) = v(k);
end
u_s(:, 1) = 0;     % Glacier head
u_s(:, Ms) = 0;    % Glacier terminus

end