function [u_s] = solver_u_core_test(visc_s, visc, AGlen_s, para)
% BETA VERSION

% Inputs:
% visc_s [Pa a]
% visc [Pa a]
% AGlen_s [Pa-3 a-1]

% Outputs:
% u_s [m a-1]

global xi Ms N dx dzeta zeta H_s hB_s W W_s...
    dzetadx dzetadx_s dhSdx_s dhBdx_s...
    iTimeStep u_s_lst enth_lst hWL Neff_lst beta2_s usurf_s_obs

% physical constants and parameters
rhoi = para.rhoi;
rhow = para.rhow;
g = para.g;
n = para.n;
type_BBC = para.type_BBC;
type_LBC = para.type_LBC;
lambda_max = para.lambda_max;
m_max = para.m_max;
kflot = para.kflot;
is_SBC_width = para.is_SBC_width;
is_flowband = para.is_flowband;
f_nye = para.f_nye;
type_SBC = para.type_SBC;

% coefficients for linear systems
L1 = 4*visc_s;
L2 = 4*visc_s.*dzetadx_s.^2 + visc_s./(ones(N,1)*H_s).^2;
L3 = 8*dzetadx_s.*visc_s;

L4 = zeros(N,Ms);
L5 = zeros(N,Ms);
L6 = zeros(N,Ms);

Ls1 = zeros(1,Ms);
Ls2 = zeros(1,Ms);
LsW = zeros(1,Ms);

LHS = zeros(N*Ms, N*Ms);
RHS = zeros(N*Ms,1);

% shallow ice approximation (SIA)
sia = @(y,x) -2*AGlen_s(y,x)*(rhoi*g*dhSdx_s(x))^n/(n+1) *...
    (H_s(x)^(n+1) - (H_s(x)-H_s(x)*zeta(y)).^(n+1));
%% Build main
%
for i = 2:Ms-1
    for j = 2:N-1
        k = (i-1)*N + j;
        RHS(k,1) = f_nye*rhoi*g*dhSdx_s(i);

        if i==2
            L4(j,i) = 4*visc_s(j,i)*(-4*dzetadx_s(j,i-1)+3*dzetadx_s(j,i)+dzetadx_s(j,i+1))/(3*dx) + ...
                4*visc_s(j,i)*dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta) + ...
                4*dzetadx_s(j,i)*(-4*visc_s(j,i-1)+3*visc_s(j,i)+visc_s(j,i+1))/(3*dx) + ...
                (visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)*(4*dzetadx_s(j,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(j,i)*visc_s(j,i)/W_s(j,i) * ...
                ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx) +...
                dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L4(N,i) = 4*visc_s(N,i)*(-4*dzetadx_s(N,i-1)+3*dzetadx_s(N,i)+dzetadx_s(N,i+1))/(3*dx) + ...
                4*visc_s(N,i)*dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta) + ...
                4*dzetadx_s(N,i)*(-4*visc_s(N,i-1)+3*visc_s(N,i)+visc_s(N,i+1))/(3*dx) + ...
                (3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)*(4*dzetadx_s(N,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(N,i)*visc_s(N,i)/W_s(N,i) * ...
                ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L4(1,i) = 4*visc_s(1,i)*(-4*dzetadx_s(1,i-1)+3*dzetadx_s(1,i)+dzetadx_s(1,i+1))/(3*dx) + ...
                4*visc_s(1,i)*dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta) + ...
                4*dzetadx_s(1,i)*(-4*visc_s(1,i-1)+3*visc_s(1,i)+visc_s(1,i+1))/(3*dx) + ...
                (-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)*(4*dzetadx_s(1,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(1,i)*visc_s(1,i)/W_s(1,i) * ...
                ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx) +...
                dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        elseif i==Ms-1
            L4(j,i) = 4*visc_s(j,i)*(-1*dzetadx_s(j,i-1)-3*dzetadx_s(j,i)+4*dzetadx_s(j,i+1))/(3*dx)+...
                4*visc_s(j,i)*dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta) +...
                4*dzetadx_s(j,i)*(-1*visc_s(j,i-1)-3*visc_s(j,i)+4*visc_s(j,i+1))/(3*dx) +...
                (visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)*(4*dzetadx_s(j,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(j,i)*visc_s(j,i)/W_s(j,i) * ...
                ((-1*W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx) +...
                dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L4(N,i) = 4*visc_s(N,i)*(-1*dzetadx_s(N,i-1)-3*dzetadx_s(N,i)+4*dzetadx_s(N,i+1))/(3*dx)+...
                4*visc_s(N,i)*dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta) +...
                4*dzetadx_s(N,i)*(-1*visc_s(N,i-1)-3*visc_s(N,i)+4*visc_s(N,i+1))/(3*dx) +...
                (3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)*(4*dzetadx_s(N,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(N,i)*visc_s(N,i)/W_s(N,i) * ...
                ((-1*W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L4(1,i) = 4*visc_s(1,i)*(-1*dzetadx_s(1,i-1)-3*dzetadx_s(1,i)+4*dzetadx_s(1,i+1))/(3*dx)+...
                4*visc_s(1,i)*dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta) +...
                4*dzetadx_s(1,i)*(-1*visc_s(1,i-1)-3*visc_s(1,i)+4*visc_s(1,i+1))/(3*dx) +...
                (-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)*(4*dzetadx_s(1,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(1,i)*visc_s(1,i)/W_s(1,i)*...
                ((-1*W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx) +...
                dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        else
            L4(j,i) = 4*visc_s(j,i)*(dzetadx(j,i)-dzetadx(j,i-1))/(dx)+...
                4*visc_s(j,i)*dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta) +...
                4*dzetadx_s(j,i)*(visc(j,i)-visc(j,i-1))/(dx) +...
                (visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)*(4*dzetadx_s(j,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(j,i)*visc_s(j,i)/W_s(j,i) *...
                ((W(j,i)-W(j,i-1))/(dx)+dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L4(N,i) = 4*visc_s(N,i)*(dzetadx(N,i)-dzetadx(N,i-1))/(dx)+...
                4*visc_s(N,i)*dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta) +...
                4*dzetadx_s(N,i)*(visc(N,i)-visc(N,i-1))/(dx) +...
                (3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)*(4*dzetadx_s(N,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(N,i)*visc_s(N,i)/W_s(N,i)*...
                ((W(N,i)-W(N,i-1))/(dx)+dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L4(1,i) = 4*visc_s(1,i)*(dzetadx(1,i)-dzetadx(1,i-1))/(dx)+...
                4*visc_s(1,i)*dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta) +...
                4*dzetadx_s(1,i)*(visc(1,i)-visc(1,i-1))/(dx) +...
                (-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)*(4*dzetadx_s(1,i)^2+1/H_s(i)^2) + ...
                2*dzetadx_s(1,i)*visc_s(1,i)/W_s(1,i)*...
                ((W(1,i)-W(1,i-1))/(dx)+dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        end

        if i==2
            L5(j,i) = 4*(-4*visc_s(j,i-1)+3*visc_s(j,i)+visc_s(j,i+1))/(3*dx) +...
                4*dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta) + ...
                2*visc_s(j,i)/W_s(j,i)*...
                ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx) +...
                dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L5(N,i) = 4*(-4*visc_s(N,i-1)+3*visc_s(N,i)+visc_s(N,i+1))/(3*dx) +...
                4*dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta) + ...
                2*visc_s(N,i)/W_s(N,i)*...
                ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L5(1,i) = 4*(-4*visc_s(1,i-1)+3*visc_s(1,i)+visc_s(1,i+1))/(3*dx) +...
                4*dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta) + ...
                2*visc_s(1,i)/W_s(1,i)*...
                ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx) +...
                dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        elseif i==Ms-1
            L5(j,i) = 4*(-visc_s(j,i-1)-3*visc_s(j,i)+4*visc_s(j,i+1))/(3*dx) +...
                4*dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta) + ...
                2*visc_s(j,i)/W_s(j,i)*...
                ((-W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx) +...
                dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L5(N,i) = 4*(-visc_s(N,i-1)-3*visc_s(N,i)+4*visc_s(N,i+1))/(3*dx) +...
                4*dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta) + ...
                2*visc_s(N,i)/W_s(N,i)*...
                ((-W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L5(1,i) = 4*(-visc_s(1,i-1)-3*visc_s(1,i)+4*visc_s(1,i+1))/(3*dx) +...
                4*dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta) + ...
                2*visc_s(1,i)/W_s(1,i)*...
                ((-W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx) +...
                dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        else
            L5(j,i) = 4*(visc(j,i)-visc(j,i-1))/(dx) +...
                4*dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta) + ...
                2*visc_s(j,i)/W_s(j,i)*...
                ((W(j,i)-W(j,i-1))/(dx) +...
                dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta));

            L5(N,i) = 4*(visc(N,i)-visc(N,i-1))/(dx) +...
                4*dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta) + ...
                2*visc_s(N,i)/W_s(N,i)*...
                ((W(N,i)-W(N,i-1))/(dx) +...
                dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta));

            L5(1,i) = 4*(visc(1,i)-visc(1,i-1))/(dx) +...
                4*dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta) + ...
                2*visc_s(1,i)/W_s(1,i)*...
                ((W(1,i)-W(1,i-1))/(dx) +...
                dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta));
        end

        if is_flowband
            if i==2
                L6(j,i) = 2/W_s(j,i)*((-4*visc_s(j,i-1)+3*visc_s(j,i)+visc_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)) *...
                    ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)) +...
                    2*visc_s(j,i)/W_s(j,i)*(...
                    (8*W_s(j,i-1)-12*W_s(j,i)+4*W_s(j,i+1))/(3*dx^2) +...
                    dzetadx_s(j,i)^2*(W_s(j-1,i)-2*W_s(j,i)+W_s(j+1,i))/(dzeta^2) +...
                    2*dzetadx_s(j,i)*(-4*(W_s(j+1,i-1)-W_s(j-1,i-1)) +...
                    3*(W_s(j+1,i)-W_s(j-1,i))+(W_s(j+1,i+1)-W_s(j-1,i+1)))/(6*dx*dzeta) +...
                    (W_s(j+1,i)-W_s(j-1,i))/(2*dzeta) *...
                    ((-4*dzetadx_s(j,i-1)+3*dzetadx_s(j,i)+dzetadx_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta)) -...
                    ((-4*W_s(j,i-1)+3*W_s(j,i)+W_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta))^2/W_s(j,i)...
                    ) - visc_s(j,i)/W_s(j,i)^2;

                L6(N,i) = 2/W_s(N,i)*((-4*visc_s(N,i-1)+3*visc_s(N,i)+visc_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)) *...
                    ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)) +...
                    2*visc_s(N,i)/W_s(N,i)*(...
                    (8*W_s(N,i-1)-12*W_s(N,i)+4*W_s(N,i+1))/(3*dx^2) +...
                    dzetadx_s(N,i)^2*(W_s(N,i)-2*W_s(N-1,i)+W_s(N-2,i))/(dzeta^2) +...
                    2*dzetadx_s(N,i)*(-4*(3*W_s(N,i-1)-4*W_s(N-1,i-1)+W_s(N-2,i-1)) +...
                    3*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))+(3*W_s(N,i+1)-4*W_s(N-1,i+1)+W_s(N-2,i+1)))/(6*dx*dzeta) +...
                    (3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta) *...
                    ((-4*dzetadx_s(N,i-1)+3*dzetadx_s(N,i)+dzetadx_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta)) -...
                    ((-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta))^2/W_s(N,i)...
                    ) - visc_s(N,i)/W_s(N,i)^2;

                L6(1,i) = 2/W_s(1,i)*((-4*visc_s(1,i-1)+3*visc_s(1,i)+visc_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)) *...
                    ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)) +...
                    2*visc_s(1,i)/W_s(1,i)*(...
                    (8*W_s(1,i-1)-12*W_s(1,i)+4*W_s(1,i+1))/(3*dx^2) +...
                    dzetadx_s(1,i)^2*(W_s(1,i)-2*W_s(2,i)+W_s(3,i))/(dzeta^2) +...
                    2*dzetadx_s(1,i)*(-4*(-3*W_s(1,i-1)+4*W_s(2,i-1)+W_s(3,i-1)) +...
                    3*(-3*W_s(1,i)+4*W_s(2,i)+W_s(3,i))+(-3*W_s(1,i+1)+4*W_s(2,i+1)+W_s(3,i+1)))/(6*dx*dzeta) +...
                    (-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta) *...
                    ((-4*dzetadx_s(1,i-1)+3*dzetadx_s(1,i)+dzetadx_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta)) -...
                    ((-4*W_s(1,i-1)+3*W_s(1,i)+W_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta))^2/W_s(1,i)...
                    ) - visc_s(1,i)/W_s(1,i)^2;
            elseif i==Ms-1
                L6(j,i) = 2/W_s(j,i)*((-visc_s(j,i-1)-3*visc_s(j,i)+4*visc_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)) *...
                    ((-W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)) +...
                    2*visc_s(j,i)/W_s(j,i)*(...
                    (4*W_s(j,i-1)-12*W_s(j,i)+8*W_s(j,i+1))/(3*dx^2) +...
                    dzetadx_s(j,i)^2*(W_s(j-1,i)-2*W_s(j,i)+W_s(j+1,i))/(dzeta^2) +...
                    2*dzetadx_s(j,i)*(-(W_s(j+1,i-1)-W_s(j-1,i-1)) -...
                    3*(W_s(j+1,i-1)-W_s(j-1,i-1))+4*(W_s(j+1,i-1)-W_s(j-1,i-1)))/(6*dx*dzeta) +...
                    (W_s(j+1,i)-W_s(j-1,i))/(2*dzeta) *...
                    ((-dzetadx_s(j,i-1)-3*dzetadx_s(j,i)+4*dzetadx_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta)) -...
                    ((-W_s(j,i-1)-3*W_s(j,i)+4*W_s(j,i+1))/(3*dx) +...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta))^2/W_s(j,i)...
                    ) - visc_s(j,i)/W_s(j,i)^2;

                L6(N,i) = 2/W_s(N,i)*((-visc_s(N,i-1)-3*visc_s(N,i)+4*visc_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)) *...
                    ((-W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)) +...
                    2*visc_s(N,i)/W_s(N,i)*(...
                    (4*W_s(N,i-1)-12*W_s(N,i)+8*W_s(N,i+1))/(3*dx^2) +...
                    dzetadx_s(N,i)^2*(W_s(N,i)-2*W_s(N-1,i)+W_s(N-2,i))/(dzeta^2) +...
                    2*dzetadx_s(N,i)*(-(3*W_s(N,i-1)-4*W_s(N-1,i-1)+W_s(N,i-1)) -...
                    3*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N,i))+4*(3*W_s(N,i+1)-4*W_s(N-1,i+1)+W_s(N,i+1)))/(6*dx*dzeta) +...
                    (3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta) *...
                    ((-dzetadx_s(N,i-1)-3*dzetadx_s(N,i)+4*dzetadx_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta)) -...
                    ((-W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta))^2/W_s(N,i)...
                    ) - visc_s(N,i)/W_s(N,i)^2;

                L6(1,i) = 2/W_s(1,i)*((-visc_s(1,i-1)-3*visc_s(1,i)+4*visc_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)) *...
                    ((-W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)) + ...
                    2*visc_s(1,i)/W_s(1,i)*(...
                    (4*W_s(1,i-1)-12*W_s(1,i)+8*W_s(1,i+1))/(3*dx^2) +...
                    dzetadx_s(1,i)^2*(W_s(1,i)-2*W_s(2,i)+W_s(3,i))/(dzeta^2) +...
                    2*dzetadx_s(1,i)*(-(-3*W_s(1,i-1)+4*W_s(2,i-1)+W_s(3,i-1)) -...
                    3*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))+4*(-3*W_s(1,i+1)+4*W_s(2,i+1)-W_s(3,i+1)))/(6*dx*dzeta) +...
                    (-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta) *...
                    ((-dzetadx_s(1,i-1)-3*dzetadx_s(1,i)+4*dzetadx_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta)) -...
                    ((-W_s(1,i-1)-3*W_s(1,i)+4*W_s(1,i+1))/(3*dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta))^2/W_s(1,i)...
                    ) - visc_s(1,i)/W_s(1,i)^2;
            else
                L6(j,i) = 2/W_s(j,i)*((visc(j,i)-visc(j,i-1))/(dx) +...
                    dzetadx_s(j,i)*(visc_s(j+1,i)-visc_s(j-1,i))/(2*dzeta)) *...
                    ((W(j,i)-W(j,i-1))/(dx) + ...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta)) +...
                    2*visc_s(j,i)/W_s(j,i)*(...
                    (W_s(j,i-1)-2*W_s(j,i)+W_s(j,i+1))/(dx^2) +...
                    dzetadx_s(j,i)^2*(W_s(j-1,i)-2*W_s(j,i)+W_s(j+1,i))/(dzeta^2) +...
                    2*dzetadx_s(j,i)*(W_s(j+1,i+1)+W_s(j-1,i-1)-W_s(j+1,i-1)-W_s(j-1,i+1))/(4*dx*dzeta) +...
                    (W_s(j+1,i)-W_s(j-1,i))/(2*dzeta) *...
                    ((dzetadx(j,i)-dzetadx(j,i-1))/(dx) +...
                    dzetadx_s(j,i)*(dzetadx_s(j+1,i)-dzetadx_s(j-1,i))/(2*dzeta)) -...
                    ((W(j,i)-W(j,i-1))/(dx) +...
                    dzetadx_s(j,i)*(W_s(j+1,i)-W_s(j-1,i))/(2*dzeta))^2/W_s(j,i)...
                    ) - visc_s(j,i)/W_s(j,i)^2;

                L6(N,i) = 2/W_s(N,i)*((visc(N,i)-visc(N,i-1))/(dx) + ...
                    dzetadx_s(N,i)*(3*visc_s(N,i)-4*visc_s(N-1,i)+visc_s(N-2,i))/(2*dzeta)) *...
                    ((W(N,i)-W(N,i-1))/(dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta)) +...
                    2*visc_s(N,i)/W_s(N,i)*(...
                    (W_s(N,i-1)-2*W_s(N,i)+W_s(N,i+1))/(dx^2) +...
                    dzetadx_s(N,i)^2*(W_s(N,i)-2*W_s(N-1,i)+W_s(N-2,i))/(dzeta^2) +...
                    2*dzetadx_s(N,i)*((3*W_s(N,i+1)-4*W_s(N-1,i+1)+W_s(N-2,i+1)) -...
                    (3*W_s(N,i-1)-4*W_s(N-1,i-1)+W_s(N-2,i-1)))/(4*dx*dzeta) +...
                    (3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta) *...
                    ((dzetadx(N,i)-dzetadx(N,i-1))/(dx) +...
                    dzetadx_s(N,i)*(3*dzetadx_s(N,i)-4*dzetadx_s(N-1,i)+dzetadx_s(N-2,i))/(2*dzeta)) -...
                    ((W(N,i)-W(N,i-1))/(dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta))^2/W_s(N,i)...
                    ) - visc_s(N,i)/W_s(N,i)^2;

                L6(1,i) = 2/W_s(1,i)*((visc(1,i)-visc(1,i-1))/(dx) +...
                    dzetadx_s(1,i)*(-3*visc_s(1,i)+4*visc_s(2,i)-visc_s(3,i))/(2*dzeta)) *...
                    ((W(1,i)-W(1,i-1))/(dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta)) +...
                    2*visc_s(1,i)/W_s(1,i)*(...
                    (W_s(1,i-1)-2*W_s(1,i)+W_s(1,i+1))/(dx^2) +...
                    dzetadx_s(1,i)^2*(W_s(1,i)-2*W_s(2,i)+W_s(3,i))/(dzeta^2) +...
                    2*dzetadx_s(1,i)*((-3*W_s(1,i+1)+4*W_s(2,i+1)-W_s(3,i+1)) -...
                    (-3*W_s(1,i-1)+4*W_s(2,i-1)-W_s(3,i-1)))/(4*dx*dzeta) +...
                    (-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta) *...
                    ((dzetadx(1,i)-dzetadx(1,i-1))/(dx) +...
                    dzetadx_s(1,i)*(-3*dzetadx_s(1,i)+4*dzetadx_s(2,i)-dzetadx_s(3,i))/(2*dzeta)) -...
                    ((W(1,i)-W(1,i-1))/(dx) +...
                    dzetadx_s(1,i)*(-3*W_s(1,i)+4*W_s(2,i)-W_s(3,i))/(2*dzeta))^2/W_s(1,i)...
                    ) - visc_s(1,i)/W_s(1,i)^2;
            end
        end
        %------------------------------------LHS---------------------------
        if i==2
            LHS(k,k-N-1) = 2*L3(j,i)/(3*dx*dzeta);
            LHS(k,k-N) = 8*L1(j,i)/(3*dx^2) - 4*L5(j,i)/(3*dx);
            LHS(k,k-N+1) = -2*L3(j,i)/(3*dx*dzeta);
            LHS(k,k-1) = L2(j,i)/dzeta^2-L3(j,i)/(2*dx*dzeta) - L4(j,i)/(2*dzeta);
            LHS(k,k) = -4*L1(j,i)/(dx^2) - 2*L2(j,i)/dzeta^2 + L5(j,i)/dx+L6(j,i);
            LHS(k,k+1) = L2(j,i)/(dzeta^2) + L3(j,i)/(2*dx*dzeta) + L4(j,i)/(2*dzeta);
            LHS(k,k+N-1) = -L3(j,i)/(6*dx*dzeta);
            LHS(k,k+N) = 4*L1(j,i)/(3*dx^2) + L5(j,i)/(3*dx);
            LHS(k,k+N+1) = L3(j,i)/(6*dx*dzeta);

        elseif i==Ms-1
            LHS(k,k-N-1) = L3(j,i)/(6*dx*dzeta);
            LHS(k,k-N) = 4*L1(j,i)/(3*dx^2) - L5(j,i)/(3*dx);
            LHS(k,k-N+1) = -L3(j,i)/(6*dx*dzeta);
            LHS(k,k-1) = L2(j,i)/(dzeta^2) + L3(j,i)/(2*dx*dzeta) - L4(j,i)/(2*dzeta);
            LHS(k,k) = -4*L1(j,i)/(dx^2) - 2*L2(j,i)/dzeta^2 - L5(j,i)/dx + L6(j,i);
            LHS(k,k+1) = L2(j,i)/(dzeta^2) - L3(j,i)/(2*dx*dzeta) + L4(j,i)/(2*dzeta);
            LHS(k,k+N-1) = -2*L3(j,i)/(3*dx*dzeta);
            LHS(k,k+N) = 8*L1(j,i)/(3*dx^2) + 4*L5(j,i)/(3*dx);
            LHS(k,k+N+1) = 2*L3(j,i)/(3*dx*dzeta);

        else
            LHS(k,k-N-1) = L3(j,i)/(4*dx*dzeta);
            LHS(k,k-N) = L1(j,i)/(dx^2) - L5(j,i)/(2*dx);
            LHS(k,k-N+1) = -L3(j,i)/(4*dx*dzeta);
            LHS(k,k-1) = L2(j,i)/(dzeta^2) - L4(j,i)/(2*dzeta);
            LHS(k,k) = -2*L1(j,i)/(dx^2) - 2*L2(j,i)/dzeta^2 + L6(j,i);
            LHS(k,k+1) = L2(j,i)/dzeta^2 + L4(j,i)/(2*dzeta);
            LHS(k,k+N-1) = -L3(j,i)/(4*dx*dzeta);
            LHS(k,k+N) = L1(j,i)/(dx^2) + L5(j,i)/(2*dx);
            LHS(k,k+N+1) = L3(j,i)/(4*dx*dzeta);
        end
    end
end
%% Build surface BC (j=N)
%
if strcmp(type_SBC, 'neum')
    for i = 1:Ms
        RHS((i-1)*N+N,1) = rhoi*g*dhSdx_s(i);
        Ls1(i) = 4*H_s(i)*dhSdx_s(i)/(1-4*H_s(i)*dzetadx_s(N,i)*dhSdx_s(i))*dzeta/dx;
        Ls2(i) = 4*H_s(i)*dhSdx_s(i)/(1-4*H_s(i)*dzetadx_s(N,i)*dhSdx_s(i))*dzeta/W_s(N,i);

        if is_SBC_width
            if i==1
                LsW(i) = (-8*W_s(N,i)+9*W_s(N,i+1)-W_s(N,i+2))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
            elseif i==2
                LsW(i) = (-4*W_s(N,i-1)+3*W_s(N,i)+W_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
            elseif i==Ms-1
                LsW(i) = (-W_s(N,i-1)-3*W_s(N,i)+4*W_s(N,i+1))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
            elseif i==Ms
                LsW(i) = (8*W_s(N,i)-9*W_s(N,i-1)+W_s(N,i-2))/(3*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
            else
                LsW(i) = (W_s(N,i+1)-W_s(N,i-1))/(2*dx) +...
                    dzetadx_s(N,i)*(3*W_s(N,i)-4*W_s(N-1,i)+W_s(N-2,i))/(2*dzeta);
            end
        end
    end

    for i = 2:Ms-1
        if i==2
            LHS(i*N, (i-1)*N) = 8*L1(N,i)/(3*dx^2) - 8/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
                L3(N,i)*(64/3*Ls1(i-1)-4*Ls2(i-1)*LsW(i-1)-8*Ls1(i))/(6*dx*dzeta) - ...
                8/3*L4(N,i)*Ls1(i)/(2*dzeta) - 4*L5(N,i)/(3*dx);
            LHS(i*N, i*N-1) = 2*L2(N,i)/(dzeta^2);
            LHS(i*N, i*N) = -12*L1(N,i)/(3*dx^2) +...
                L2(N,i)*(2*Ls1(i)+Ls2(i)*LsW(i)-2)/(dzeta^2) + ...
                L3(N,i)*(-24*Ls1(i-1)+6*Ls1(i)+Ls2(i)*LsW(i)-Ls1(i+1))/(6*dx*dzeta) + ...
                L4(N,i)*(2*Ls1(i)+Ls2(i)*LsW(i))/(2*dzeta) + 3*L5(N,i)/(3*dx);
            LHS(i*N, (i+1)*N) = 4*L1(N,i)/(3*dx^2) + 2/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
                L3(N,i)*(8/3*Ls1(i-1)+2*Ls1(i)+Ls2(i+1)*LsW(i+1))/(6*dx*dzeta) + ...
                L4(N,i)*(2/3*Ls1(i))/(2*dzeta) + L5(N,i)/(3*dx);
            LHS(i*N, (i+2)*N) = L3(N,i)*Ls1(i+1)/(6*dx*dzeta);

        elseif i==Ms-1
            LHS(i*N,(i-2)*N) = L3(N,i)*Ls1(i-1)/(6*dx*dzeta);
            LHS(i*N,(i-1)*N) = 4*L1(N,i)/(3*dx^2) - 2/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
                L3(N,i)*(-Ls2(i-1)*LsW(i-1)+2*Ls1(i)+8/3*Ls1(i+1))/(6*dx*dzeta)...
                -2/3*L4(N,i)*Ls1(i)/(2*dzeta) - L5(N,i)/(3*dx);
            LHS(i*N,i*N-1) = 2*L2(N,i)/(dzeta^2);
            LHS(i*N,i*N) = -12*L1(N,i)/(3*dx^2) +...
                L2(N,i)*(-2*Ls1(i)+Ls2(i)*LsW(i)-2)/(dzeta^2) + ...
                L3(N,i)*(-Ls1(i-1)+6*Ls1(i)-3*Ls2(i)*LsW(i)-24*Ls1(i+1))/(6*dx*dzeta) + ...
                L4(N,i)*(-2*Ls1(i)+Ls2(i)*LsW(i))/(2*dzeta) - 3*L5(N,i)/(3*dx);
            LHS(i*N,(i+1)*N) = 8*L1(N,i)/(3*dx^2) + 8/3*L2(N,i)*Ls1(i)/(dzeta^2) + ...
                L3(N,i)*(-8*Ls1(i)+64/3*Ls1(i+1)+4*Ls2(i+1)*LsW(i+1))/(6*dx*dzeta) + ...
                8/3*L4(N,i)*Ls1(i)/(2*dzeta) + 4*L5(N,i)/(3*dx);

        else
            LHS(i*N,(i-2)*N) = L3(N,i)*Ls1(i-1)/(4*dx*dzeta);
            LHS(i*N,(i-1)*N) = L1(N,i)/(dx^2) - L2(N,i)*Ls1(i)/(dzeta^2) - ...
                L3(N,i)*Ls2(i-1)*LsW(i-1)/(4*dx*dzeta) -...
                L4(N,i)*Ls1(i)/(2*dzeta) - L5(N,i)/(2*dx);
            LHS(i*N,i*N-1) = 2*L2(N,i)/(dzeta^2);
            LHS(i*N,i*N) = -2*L1(N,i)/(dx^2) + L2(N,i)*(Ls2(i)*LsW(i)-2)/(dzeta^2) -...
                L3(N,i)*(Ls1(i-1)+Ls1(i+1))/(4*dx*dzeta) + L4(N,i)*Ls2(i)*LsW(i)/(2*dzeta);
            LHS(i*N,(i+1)*N) = L1(N,i)/(dx^2) + L2(N,i)*Ls1(i)/(dzeta^2) +...
                L3(N,i)*Ls2(i+1)*LsW(i+1)/(4*dx*dzeta) +...
                L4(N,i)*Ls1(i)/(2*dzeta) + L5(N,i)/(2*dx);
            LHS(i*N,(i+2)*N) = L3(N,i)*Ls1(i+1)/(4*dx*dzeta);
        end
    end
else % Dirichlet
    for i = 2:Ms-1
        LHS(i*N,i*N) = 1;
        RHS(i*N,1) = usurf_s_obs(i);
    end
end
%% Build basal BC (j=1)
%
if strcmpi(type_BBC,'zero')
    for i = 2:Ms-1
        LHS((i-1)*N+1,(i-1)*N+1) = 1;
        RHS((i-1)*N+1,1) = 0;
    end
elseif strcmpi(type_BBC, 'CFlaw_polyT')
    ub_s = u_s_lst(1,:);

    % effective pressure should be coupled to subglacial hydrology
    if iTimeStep==1
        Neff_lst = (1-kflot).*(rhoi*g*H_s);
    end

    % Following Flowers (2011)
    Cb = 0.84*m_max;
    reg_schoof = 0.01; % reg_schoof is a regularization term
    Lb_CFL = 4*dzeta.*AGlen_s(1,:).*H_s.*(Cb.^n).*(Neff_lst.^n).*m_max ./...
        (m_max.*ub_s + (Cb.^n).*lambda_max.*AGlen_s(1,:).*(Neff_lst.^n)) + reg_schoof;

    for i=2:Ms-1
        if iTimeStep>1 && enth_lst.is_TEMP(i)==1 % slide on temperate bed
            if i==2
                LHS((i-1)*N+1,(i-2)*N+1) = 8*L1(1,i)/(3*dx^2) -...
                    4*Lb_CFL(i-1)*L3(1,i)/(6*dx*dzeta) -...
                    4*L5(1,i)/(3*dx);
                LHS((i-1)*N+1,(i-1)*N+1) = -12*L1(1,i)/(3*dx^2) -...
                    (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) +...
                    3*L3(1,i)*Lb_CFL(i)/(6*dx*dzeta) +...
                    Lb_CFL(i)*L4(1,i)/(2*dzeta) +...
                    3*L5(1,i)/(3*dx) + L6(1,i);
                LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/dzeta^2;
                LHS((i-1)*N+1,i*N+1) = 4*L1(1,i)/(3*dx^2) +...
                    Lb_CFL(i+1)*L3(1,i)/(6*dx*dzeta) +...
                    L5(1,i)/(3*dx);
            elseif i==Ms-1
                LHS((i-1)*N+1,(i-2)*N+1) = 4*L1(1,i)/(3*dx^2) -...
                    Lb_CFL(i-1)*L3(1,i)/(6*dx*dzeta) -...
                    L5(1,i)/(3*dx);
                LHS((i-1)*N+1,(i-1)*N+1) = -12*L1(1,i)/(3*dx^2) -...
                    (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) -...
                    3*Lb_CFL(i)*L3(1,i)/(6*dx*dzeta) +...
                    Lb_CFL(i)*L4(1,i)/(2*dzeta) -...
                    3*L5(1,i)/(3*dx) + L6(1,i);
                LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/dzeta^2;
                LHS((i-1)*N+1,i*N+1) = 8*L1(1,i)/(3*dx^2) +...
                    4*Lb_CFL(i+1)*L3(1,i)/(6*dx*dzeta) +...
                    4*L5(1,i)/(3*dx);
            else
                LHS((i-1)*N+1,(i-2)*N+1) = L1(1,i)/(dx^2) -...
                    Lb_CFL(i-1)*L3(1,i)/(4*dx*dzeta) -...
                    L5(1,i)/(2*dx);
                LHS((i-1)*N+1,(i-1)*N+1) = -2*L1(1,i)/(dx^2) -...
                    (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) +...
                    Lb_CFL(i)*L4(1,i)/(2*dzeta) + L6(1,i);
                LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
                LHS((i-1)*N+1,i*N+1) = L1(1,i)/(dx^2) +...
                    Lb_CFL(i+1)*L3(1,i)/(4*dx*dzeta) +...
                    L5(1,i)/(2*dx);
            end
        else % frozen to bedrock
            LHS((i-1)*N+1,(i-1)*N+1) = 1;
            RHS((i-1)*N+1,1) = 0;
        end
    end
elseif strcmpi(type_BBC, 'CFlaw_isoT')
    ub_s = u_s_lst(1,:);

    % Effective pressure (N)
    if iTimeStep==1
        Neff_lst = (1-kflot).*(rhoi*g*H_s);
    end

    % Following Flowers (2011)
    Cb = 0.84*m_max;
    reg_schoof = 0.01; % reg_schoof is a regularization term
    Lb_CFL = 4*dzeta.*AGlen_s(1,:).*H_s.*(Cb.^n).*(Neff_lst.^n).*m_max ./...
        (m_max.*ub_s + (Cb.^n).*lambda_max.*AGlen_s(1,:).*(Neff_lst.^n)) + reg_schoof;

    for i=2:Ms-1
        RHS((i-1)*N+1,1) = rhoi*g*dhSdx_s(i);
        if i==2
            LHS((i-1)*N+1,(i-2)*N+1) = 8*L1(1,i)/(3*dx^2) -...
                4*Lb_CFL(i-1)*L3(1,i)/(6*dx*dzeta) -...
                4*L5(1,i)/(3*dx);
            LHS((i-1)*N+1,(i-1)*N+1) = -12*L1(1,i)/(3*dx^2) -...
                (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) +...
                3*L3(1,i)*Lb_CFL(i)/(6*dx*dzeta) +...
                Lb_CFL(i)*L4(1,i)/(2*dzeta) +...
                3*L5(1,i)/(3*dx) + L6(1,i);
            LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
            LHS((i-1)*N+1,i*N+1) = 4*L1(1,i)/(3*dx^2) +...
                Lb_CFL(i+1)*L3(1,i)/(6*dx*dzeta) +...
                L5(1,i)/(3*dx);
        elseif i==Ms-1
            LHS((i-1)*N+1,(i-2)*N+1) = 4*L1(1,i)/(3*dx^2) -...
                Lb_CFL(i-1)*L3(1,i)/(6*dx*dzeta) -...
                L5(1,i)/(3*dx);
            LHS((i-1)*N+1,(i-1)*N+1) = -12*L1(1,i)/(3*dx^2) -...
                (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) -...
                3*Lb_CFL(i)*L3(1,i)/(6*dx*dzeta) +...
                Lb_CFL(i)*L4(1,i)/(2*dzeta) -...
                3*L5(1,i)/(3*dx) + L6(1,i);
            LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
            LHS((i-1)*N+1,i*N+1) = 8*L1(1,i)/(3*dx^2) +...
                4*Lb_CFL(i+1)*L3(1,i)/(6*dx*dzeta) +...
                4*L5(1,i)/(3*dx);
        else
            LHS((i-1)*N+1,(i-2)*N+1) = L1(1,i)/(dx^2) -...
                Lb_CFL(i-1)*L3(1,i)/(4*dx*dzeta) -...
                L5(1,i)/(2*dx);
            LHS((i-1)*N+1,(i-1)*N+1) = -2*L1(1,i)/(dx^2) -...
                (2+Lb_CFL(i))*L2(1,i)/(dzeta^2) +...
                Lb_CFL(i)*L4(1,i)/(2*dzeta) + L6(1,i);
            LHS((i-1)*N+1,(i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
            LHS((i-1)*N+1,i*N+1) = L1(1,i)/(dx^2) +...
                Lb_CFL(i+1)*L3(1,i)/(4*dx*dzeta) +...
                L5(1,i)/(2*dx);
        end
    end
elseif strcmpi(type_BBC, 'LFlaw') % linear friction law
    Lb1_LFL = 4*dzeta.*H_s.*dhBdx_s./(1-4*H_s.*dhBdx_s.*dzetadx_s(1,:))/(dx);
    Lb2_LFL = 2*dzeta.*H_s.*beta2_s./visc_s(1,:)./(1-4*H_s.*dhBdx_s.*dzetadx_s(1,:));

    for i = 2:Ms-1
        RHS((i-1)*N+1,1) = rhoi*g*dhSdx_s(i);
        if i==2
            LHS((i-1)*N+1, (i-2)*N+1) = 8*L1(1,i)/(3*dx^2) +...
                8*Lb1_LFL(i)*L2(1,i)/(3*dzeta^2) +...
                (64*Lb1_LFL(i-1)/3-4*Lb2_LFL(i-1)-8*Lb1_LFL(i))*L3(1,i)/(6*dx*dzeta) -...
                8/3*Lb1_LFL(i)*L4(1,i)/(2*dzeta) - 4*L5(1,i)/(3*dx);
            LHS((i-1)*N+1, (i-1)*N+1) = -12*L1(1,i)/(3*dx^2) -...
                (2+2*Lb1_LFL(i)+Lb2_LFL(i))*L2(1,i)/(dzeta^2) +...
                (-24*Lb1_LFL(i-1)+6*Lb1_LFL(i)+3*Lb2_LFL(i)-Lb1_LFL(i+1))*L3(1,i)/(6*dx*dzeta) +...
                (2*Lb1_LFL(i)+Lb2_LFL(i))*L4(1,i)/(2*dzeta) +...
                3*L5(1,i)/(3*dx) + L6(1,i);
            LHS((i-1)*N+1, (i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
            LHS((i-1)*N+1, i*N+1) = 4*L1(1,i)/(3*dx^2) -...
                2/3*Lb1_LFL(i)*L2(1,i)/(dzeta^2) +...
                (8/3*Lb1_LFL(i-1)+2*Lb1_LFL(i)+Lb2_LFL(i+1))*L3(1,i)/(6*dx*dzeta) +...
                2/3*Lb1_LFL(i)*L4(1,i)/(2*dzeta) + L5(1,i)/(3*dx);
            LHS((i-1)*N+1, (i+1)*N+1) = Lb1_LFL(i)*L3(1,i)/(6*dx*dzeta);

        elseif i==Ms-1
            LHS((i-1)*N+1, (i-3)*N+1) = Lb1_LFL(i-1)*L3(1,i)/(6*dx*dzeta);
            LHS((i-1)*N+1, (i-2)*N+1) = 4*L1(1,i)/(3*dx^2) +...
                2/3*Lb1_LFL(i)*L2(1,i)/(dzeta^2) +...
                (-Lb2_LFL(i-1)+2*Lb1_LFL(i)+8/3*Lb1_LFL(i+1))*L3(1,i)/(6*dx*dzeta) -...
                2/3*Lb1_LFL(i)*L4(1,i)/(2*dzeta) - L5(1,i)/(3*dx);
            LHS((i-1)*N+1, (i-1)*N+1) = -12*L1(1,i)/(3*dx^2) +...
                (-2+2*Lb1_LFL(i)-Lb2_LFL(i))*L2(1,i)/(dzeta^2) + ...
                (-Lb1_LFL(i-1)+6*Lb1_LFL(i)-3*Lb2_LFL(i)-24*Lb1_LFL(i+1))*L3(1,i)/(6*dx*dzeta) +...
                (-2*Lb1_LFL(i)+Lb2_LFL(i))*L4(1,i)/(2*dzeta) -...
                3*L5(1,i)/(3*dx) + L6(1,i);
            LHS((i-1)*N+1, (i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
            LHS((i-1)*N+1, i*N+1) = 8*L1(1,i)/(3*dx^2) -...
                8/3*Lb1_LFL(i)*L2(1,i)/(dzeta^2) +...
                (-8*Lb1_LFL(i)+64/3*Lb1_LFL(i+1)+4*Lb2_LFL(i+1))*L3(1,i)/(6*dx*dzeta) +...
                8/3*Lb1_LFL(i)*L4(1,i)/(2*dzeta) + 4*L5(1,i)/(3*dx);

        else
            LHS((i-1)*N+1, (i-3)*N+1) = Lb1_LFL(i-1)*L3(1,i)/(4*dx*dzeta);
            LHS((i-1)*N+1, (i-2)*N+1) = L1(1,i)/(dx^2) +...
                Lb1_LFL(i)*L2(1,i)/(dzeta^2) -...
                Lb2_LFL(i-1)*L3(1,i)/(4*dx*dzeta) -...
                Lb1_LFL(i)*L4(1,i)/(2*dzeta) - L5(1,i)/(2*dx);
            LHS((i-1)*N+1, (i-1)*N+1) = -2*L1(1,i)/(dx^2) -...
                (2+Lb2_LFL(i))*L2(1,i)/(dzeta^2) -...
                (Lb1_LFL(i+1)+Lb1_LFL(i-1))*L3(1,i)/(4*dx*dzeta) +...
                Lb2_LFL(i)*L4(1,i)/(2*dzeta) + L6(1,i);
            LHS((i-1)*N+1, (i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
            LHS((i-1)*N+1, i*N+1) = L1(1,i)/(dx^2) -...
                Lb1_LFL(i)*L2(1,i)/(dzeta^2) +...
                Lb2_LFL(i+1)*L3(1,i)/(4*dx*dzeta) +...
                Lb1_LFL(i)*L4(1,i)/(2*dzeta) + L5(1,i)/(2*dx);
            LHS((i-1)*N+1, (i+1)*N+1) = Lb1_LFL(i+1)*L3(1,i)/(4*dx*dzeta);
        end
    end
elseif strcmpi(type_BBC, 'LFlaw_simple') % simplified linear friction law
    Lb2_LFL = 2.*dzeta.*H_s.*beta2_s./visc_s(1,:);
    for i = 2:Ms-1
        RHS((i-1)*N+1,1) = rhoi*g*dhSdx_s(i);
        LHS((i-1)*N+1, (i-2)*N+1) = L1(1,i)/(dx^2) -...
            Lb2_LFL(i-1)*L3(1,i)/(4*dx*dzeta) - L5(1,i)/(2*dx);
        LHS((i-1)*N+1, (i-1)*N+1) = -2*L1(1,i)/(dx^2) -...
            (2+Lb2_LFL(i))*L2(1,i)/(dzeta^2) +...
            Lb2_LFL(i)*L4(1,i)/(2*dzeta) + L6(1,i);
        LHS((i-1)*N+1, (i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
        LHS((i-1)*N+1, i*N+1) = L1(1,i)/(dx^2) +...
            Lb2_LFL(i+1)*L3(1,i)/(4*dx*dzeta) + L5(1,i)/(2*dx);
    end
elseif strcmpi(type_BBC, 'LFlaw_E2') % linear friction law for ISMIP-HOM E2
    Lb1_LFL = 4.*dzeta.*H_s.*dhBdx_s./(1 - 4.*H_s.*dhBdx_s.*dzetadx_s(1,:))./dx;
    Lb2_LFL = zeros(N,Ms);
    xi_s = main2staggerX(xi);
    for i = 2:Ms-1
        if xi_s(i) >= 2200 && xi_s(i) <= 2500
            %             if  xi(i) >= 2200 && xi(i) <= 2500
            RHS((i-1)*N+1,1) = rhoi*g*dhSdx_s(i);

            LHS((i-1)*N+1, (i-3)*N+1) = Lb1_LFL(i-1)*L3(1,i)/(4*dx*dzeta);
            LHS((i-1)*N+1, (i-2)*N+1) = L1(1,i)/(dx^2) +...
                Lb1_LFL(i)*L2(1,i)/(dzeta^2) -...
                Lb2_LFL(i-1)*L3(1,i)/(4*dx*dzeta) -...
                Lb1_LFL(i)*L4(1,i)/(2*dzeta) - L5(1,i)/(2*dx);
            LHS((i-1)*N+1, (i-1)*N+1) = -2*L1(1,i)/(dx^2) -...
                (2+Lb2_LFL(i))*L2(1,i)/(dzeta^2) -...
                (Lb1_LFL(i+1)+Lb1_LFL(i-1))*L3(1,i)/(4*dx*dzeta) +...
                Lb2_LFL(i)*L4(1,i)/(2*dzeta) + L6(1,i);
            LHS((i-1)*N+1, (i-1)*N+2) = 2*L2(1,i)/(dzeta^2);
            LHS((i-1)*N+1, i*N+1) = L1(1,i)/(dx^2) -...
                Lb1_LFL(i)*L2(1,i)/(dzeta^2) +...
                Lb2_LFL(i+1)*L3(1,i)/(4*dx*dzeta) +...
                Lb1_LFL(i)*L4(1,i)/(2*dzeta) + L5(1,i)/(2*dx);
            LHS((i-1)*N+1, (i+1)*N+1) = Lb1_LFL(i+1)*L3(1,i)/(4*dx*dzeta);
        else
            LHS((i-1)*N+1,(i-1)*N+1) = 1;
            RHS((i-1)*N+1,1) = 0;
        end
    end
else
    disp('ERROR: type_BBC should be zero, CFlaw_polyT, CFlaw_isoT, LFlaw, LFlaw_simple, LFlaw_E2')
end
%% Build lateral BC
%---------------------(head, i=1)------------------------
% upper limit
for j = 1:N
    LHS(j,j) = 1;
    RHS(j,1) = 0; % sia(j,1);
end
%---------------------(terminus, i=Ms)--------------------
% lower limit
% zero velocity at the terminus
if strcmpi(type_LBC,'zero')
    if isempty(usurf_s_obs)
        for j = 1:N
            LHS((Ms-1)*N+j,(Ms-1)*N+j) = 1;
            RHS((Ms-1)*N+j,1) = 0; % sia(j,Ms)
        end
    else
        for j = 1:N
            LHS((Ms-1)*N+j,(Ms-1)*N+j) = 1;
            RHS((Ms-1)*N+j,1) = usurf_s_obs(Ms);
        end
    end

    % calving front
elseif strcmpi(type_LBC,'calv')
    % hWL: elevation of water level
    Lcf1 = zeros(N,1);
    for j = 1:N
        Lcf1(j) = rhoi*g*(1-zeta(j))/(4*visc_s(j,Ms))...
            + rhow*g*min([zeta(j)-(hWL-hB_s(Ms))/H_s(Ms), 0])/(4*visc_s(j,Ms));
    end

    slope_LTG = -0.06;
    for j = 2:N-1
        LHS((Ms-2)*N+j,(Ms-1)*N+j) = 2*L1(j,Ms)/(dx^2);
        RHS((Ms-1)*N+j,1) = rhoi*g*slope_LTG - 2*L1(j,Ms)*Lcf1(j)/(dx)...
            - L3(j,Ms)*(Lcf1(j+1)-Lcf1(j-1))/(2*dzeta) - L5(j,Ms)*Lcf1(j);

        if j==2
            LHS((Ms-1)*N+j-1,(Ms-1)*N+j) = L1(j,Ms)*dzetadx_s(j,Ms)/(dx*dzeta)...
                + L2(j,Ms)/(dzeta^2) - L3(j,Ms)*dzetadx_s(j,Ms)/(2*dzeta^2)...
                - L4(j,Ms)/(2*dzeta) + L5(j,Ms)*dzetadx_s(j,Ms)/(2*dzeta);
            LHS((Ms-1)*N+j,(Ms-1)*N+j) = - 2*L1(j,Ms)/(dx^2) - 2*L2(j,Ms)/(dzeta^2) ...
                + L3(j,Ms)*(dzetadx_s(j+1,Ms)+dzetadx_s(j-1,Ms))/(4*dzeta^2) + L6(j,Ms);
            LHS((Ms-1)*N+j+1,(Ms-1)*N+j) = -L1(j,Ms)*dzetadx_s(j,Ms)/(dx*dzeta)...
                + L2(j,Ms)/(dzeta^2) + L4(j,Ms)/(2*dzeta) - L5(j,Ms)*dzetadx_s(j,Ms)/(2*dzeta);
            LHS((Ms-1)*N+j+2,(Ms-1)*N+j) = -L3(j,Ms)*dzetadx_s(j+1,Ms)/(4*dzeta^2);
        elseif j==N-1
            LHS((Ms-1)*N+j-2,(Ms-1)*N+j) = -L3(j,Ms)*dzetadx_s(j,Ms)/(4*dzeta^2);
            LHS((Ms-1)*N+j-1,(Ms-1)*N+j) = L1(j,Ms)*dzetadx_s(j,Ms)/(dx*dzeta)...
                + L2(j,Ms)/(dzeta^2) - L4(j,Ms)/(2*dzeta) + L5(j,Ms)*dzetadx_s(j,Ms)/(2*dzeta);
            LHS((Ms-1)*N+j,(Ms-1)*N+j) = -2*L1(j,Ms)/(dx^2) - 2*L2(j,Ms)/(dzeta^2)...
                + L3(j,Ms)*(2*dzetadx_s(j+1,Ms)+dzetadx_s(j-1,Ms))/(4*dzeta^2) + L6(j,Ms);
            LHS((Ms-1)*N+j+1,(Ms-1)*N+j) = -L1(j,Ms)*dzetadx_s(j,Ms)/(dx*dzeta)...
                + L2(j,Ms)/(dzeta^2) - L3(j,Ms)*dzetadx_s(j+1,Ms)/(2*dzeta^2)...
                + L4(j,Ms)/(2*dzeta) - L5(j,Ms)*dzetadx_s(j,Ms)/(2*dzeta);
        else
            LHS((Ms-1)*N+j-2,(Ms-1)*N+j) = -L3(j,Ms)*dzetadx_s(j-1,Ms)/(4*dzeta^2);
            LHS((Ms-1)*N+j-1,(Ms-1)*N+j) = L1(j,Ms)*dzetadx_s(j,Ms)/(dx*dzeta)...
                + L2(j,Ms)/(dzeta^2) - L4(j,Ms)/(2*dzeta) + L5(j,Ms)*dzetadx_s(j,Ms)/(2*dzeta);
            LHS((Ms-1)*N+j,(Ms-1)*N+j) = -2*L1(j,Ms)/(dx^2) - 2*L2(j,Ms)/(dzeta^2)...
                + L3(j,Ms)*(dzetadx_s(j+1,Ms)+dzetadx_s(j-1,Ms))/(4*dzeta^2) + L6(j,Ms);
            LHS((Ms-1)*N+j+1,(Ms-1)*N+j) = -L1(j,Ms)*dzetadx_s(j,Ms)/(dx*dzeta)...
                + L2(j,Ms)/(dzeta^2) + L4(j,Ms)/(2*dzeta) - L5(j,Ms)*dzetadx_s(j,Ms)/(2*dzeta);
            LHS((Ms-1)*N+j+2,(Ms-1)*N+j) = -L3(j,Ms)*dzetadx_s(j+1,Ms)/(4*dzeta^2);
        end
    end
end

%% Solve linear system
%
v = LHS\RHS;

u_s = zeros(N, Ms);
for k = 1:N*Ms
    if fix(k/N)==k/N
        i = k/N;
    else
        i = fix(k/N) + 1;
    end
    j = k-(i-1)*N;

    u_s(j,i) = v(k);
end

if ~isempty(usurf_s_obs)
    u_s(:,Ms) = usurf_s_obs(end);    % Glacier terminus
end

end